### ISSUE TITLE
Client/Server repo reorganisation

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#122]
So we should think a bit more about how we want to server react and express files for the app.
How much can/should be served locally from the monoliths (for this first installation), and how to best organize to support online versions in the future.

Here are 3 options:
- Keep them together – Express and React files sit on the same machine (with all the React files inside a specific client folder), and Express does double duty: serving the React files and also serving API requests (e.g.,  Express on port 80 on Heroku or DigitalOcean)
- Split them apart (our current setup) – Host the Express API on one machine, and the React app on another.(e.g., React app served by Netlify, API server running on a Heroku) 
- Put the API behind a proxy – Express and React app files sit on the same machine, but served by different servers (e.g., NGINX webserver proxies API requests to the API server, and also serves React static files)

For ease-of-deployment I am in favor of the **first option,** but this requires some reorg of the github repo: specifically moving server stuff out of the server folder and into the top layer (this will also allow us to run easily on heroku, which we can't do under the current setup). The  root project folder then houses all the server-related stuff. The 'web-client' folder stays where it is and contains the entire React application. 

Serving both react and express from the same app requires a little bit of work on the server end, so @joseph-allen can you verify this plan works for you before I start? thanks

References: https://daveceddia.com/deploy-react-express-app-heroku/ https://coursework.vschool.io/deploying-mern-with-heroku/

**Comment by joseph-allen** [comment]
doesn't the react app also have to run locally when there is no internet connection, I have not used heroku before, but locally hosting the app can be done by running `yarn start` and im sure express can handle that.

**Comment by dhowe** [comment]
Yes, but so would the server (at least for the initial installation)... 
So there are two options then:
1a) apache serves the static files (port 80), a local node server serves the api from one monolith
1b) apache serves the static files (port 80), heroku serves the api
2) a local node server serves both with a flag to start-server for one monolith 

Either is fine for me, the advantage to 2) is that whatever machine you want to host things (or test them), you simply pull from github and do npm start, and everything is running.

**Comment by dhowe** [comment]
But in any case, do you mind if I move the server stuff into the top-level so that we have the heroku option?

**Comment by joseph-allen** [comment]
yeah sounds good, go for it :) shouldn't change the web-client stuff.

**Comment by dhowe** [comment]
done
