### ISSUE TITLE
Version I Pilot

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#131]
Pilot Venue: Friday, May 17 @ Regent Trading Estate Showroom

See [UX_Pilot_Plan](https://github.com/dhowe/spectre/blob/master/web-client/UX_PILOT_PLAN.MD)

NOTE: We need to standardize on a browser for dev/testing:  I would suggest the RPI default which is Chromium. Please download and use it for _all_ dev testing regardless of your platform (links for [mac](https://chromium.woolyss.com/download/en/#mac), [lin](https://chromium.woolyss.com/download/en/#linux), [win](https://chromium.woolyss.com/download/en/)).

**Functionality**
--------------
- All UX pages through 'Influence a Celeb' [f36] 
- 'Intro to Spectre' and 'Intro to Ocean' videos
- Predefined elements:
  - Most similar users (from db)
  - Influenced-by factors (from db)
- Placeholders for: 
  - Animations

**Not included:**
--------------
- UX pages after 'Influence a Celeb' [f36] 
- OCEAN Target Drawer
- Animations (need still placeholders)
- Validation of user input (email, etc)
- Verification of user responses
- Timers

**Back-end**
--------------
- New routes for all functionality through [f36]
- Full db schema through [f36]

<br/>

**Comment by joseph-allen** [comment]
Outstanding issues:
*intro video autoplay [ ] 
* intro video thumbnail [ ] 
* center intro video, add title like intro to ocean has? [ ] 
*gender selector color (should be blue not red) [ ] 
* searching for button in better position on screen with space inbetween buttons [ ] 
* influence a follower, some sort of vidual feedback on follower click, or at least making it clear there is no choice at the moment [ ] 
* all sliders larger, thicker [ ] 
* center insight style radiogroup [ ] 
*  color blue insight style radiogroup [ ] 
* intro to ocean, bigger title? [ ] 
* intro to ocean autoplay [ ] 
* center pick a side preferances [ ] 
* get list of influences for influence by(@Daniel am i right in thinking this is in the user session?) [ ] 
* build entire ad generator [ ] 
* political data - too many options for screen, put more space or into columns? [ ] 
* * home data - too many options for screen, put more space or into columns? [ ] 
* targets found, correctly scale UK map [ ] 
* nicer ending than "end for now" [ ] 
Bugs:
* aaron is claiming the videos aren't working in chromium, can anybody confirm they have worked on the monoliths? @Daniel or @Bill Posters [ ]

**Comment by joseph-allen** [comment]
@aaronalbinson @dhowe

**Comment by dhowe** [comment]
> get list of influences for influence by(@daniel am i right in thinking this is in the user session?)

yes, it will be: @billposters I need the text for this

**Comment by joseph-allen** [comment]
if it's not ready now will it be by tomorrow morning?

**Comment by dhowe** [comment]
should be there in the user now:

![image](https://user-images.githubusercontent.com/737638/57894057-5c507800-7813-11e9-8f4a-6e341c68f6e0.png)

**Comment by joseph-allen** [comment]
how do they appear there? Do I have to play the game? Also pressing space bar during the game causes an error.

**Comment by dhowe** [comment]
I cant recreate the space bar issue.
