### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 10.x

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#142]
Testing on the RPI:
```

yarn run v1.16.0
warning ../package.json: No license field
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/App.scss
Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 10.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
```

**Comment by dhowe** [comment]
reinstallation of node-gyp followed by  `$ npm install node-sass` may fix this, 
but currently the rpi is pinned due to attempted installation of mongodb from source (which has been running for several hours), so have to wait and test this later. If not, we'll have to either remove node-sass or find different server hardware

**Comment by joseph-allen** [comment]
have you seen [this](https://github.com/sass/node-sass/issues/1764)

**Comment by dhowe** [comment]
no, but I got i just got it fixed via the commands above... all good
