### ISSUE TITLE
Pilot page mockups

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#148]
Add images below, one image per 'comment'...

**Comment by billposters** [comment]
![30_Pick_A_side_mockup](https://user-images.githubusercontent.com/48989022/57895549-1a8bf580-7844-11e9-8cfe-da0bb466bd75.jpg)

**Comment by billposters** [comment]
![33_Design_tool](https://user-images.githubusercontent.com/48989022/57895559-24adf400-7844-11e9-89bf-17929e0171b6.jpg)

**Comment by billposters** [comment]
![Step_3_AI_is_the_future_of_Data](https://user-images.githubusercontent.com/48989022/57895993-6c357f80-7846-11e9-931a-38d0875884b0.jpg)

**Comment by billposters** [comment]
![Step_3_Intro_Influence_A_Celebrity](https://user-images.githubusercontent.com/48989022/57895998-76f01480-7846-11e9-9136-fe1b9268dea9.jpg)

**Comment by billposters** [comment]
![Step_3_pick-a-statement](https://user-images.githubusercontent.com/48989022/57896317-1eba1200-7848-11e9-8f3c-dba6ac374427.jpg)

**Comment by billposters** [comment]
![Step_3_feels_good_doesn't_it](https://user-images.githubusercontent.com/48989022/57896448-b586ce80-7848-11e9-97b6-dd26ef8fea16.jpg)

**Comment by billposters** [comment]
![step_3_pointing_at_user](https://user-images.githubusercontent.com/48989022/57896578-4cec2180-7849-11e9-9aaf-91bdb6468a10.jpg)

**Comment by joseph-allen** [comment]
not sure what all these are for, me and Aaron are going to bed now though
