### ISSUE TITLE
Political Preference 1D Slider

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#158]
Is this what you intended? I imagine not, but should we go with a single slider for consistency?

![image](https://user-images.githubusercontent.com/737638/57898139-c70aaf00-7825-11e9-935f-4d0a1660a8bb.png)

**Comment by joseph-allen** [comment]
the final intention will be a 2d slider, but we wanted to keep it simple for now

**Comment by dhowe** [comment]
Let's use a single slider instead. 

Barney, 'conservative' to 'liberal' OR 'left' to 'right' ?

**Comment by joseph-allen** [comment]
ah that's much easier, I'll do this one now :)

**Comment by joseph-allen** [comment]
apologies @dhowe my internet is incredibly flakey. The searching for page no longer links to the next page, is that intentional?

**Comment by dhowe** [comment]
local or netlify?

**Comment by joseph-allen** [comment]
local

**Comment by dhowe** [comment]
should be fixed now if you pull

also, can you take a look at #54 next ? thnx
