### ISSUE TITLE
Component: Game

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#16]
placeholder game component until we recieve further details

**Comment by joseph-allen** [comment]
![image](https://user-images.githubusercontent.com/7880824/56048997-798bb580-5d40-11e9-83ec-a722fd3f6916.png)

**Comment by joseph-allen** [comment]
@dhowe source code for this one?

**Comment by dhowe** [comment]
here: https://github.com/dhowe/spectre/tree/master/web-client/src/Canvas/brands
