### ISSUE TITLE
Cursor stuck as Circle after Dark-Ad page

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#161]
![image](https://user-images.githubusercontent.com/737638/57899655-dd1b6e00-782b-11e9-845b-7164d6505b42.png)

**Comment by joseph-allen** [comment]
https://stackoverflow.com/questions/17842984/google-chrome-shows-gray-circle-cursor

seems to be to do with emulating a mobile device.

**Comment by dhowe** [comment]
Correct :)
