### ISSUE TITLE
Interstitials: fade in, fade-out

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#166]
Instead of a ‘next’ button, we need every page (@billposters pls confirm this) with only text to fade in and out on a timer, based on the number of words/lines on the page

**Comment by aaronalbinson** [comment]
See https://github.com/dhowe/spectre/commit/b97adbee92400606a8356a7fbe97f094104eee40 on how to do this within this project. (initial setup is complete)

**Comment by billposters** [comment]
Have added intersticial timer requirements in the google doc action plan

**Comment by joseph-allen** [comment]
link the requirements? This generally seems like a bad idea as we don't know individuals reading times. I would suggest descoping this unless it really adds a lot to the UX

**Comment by dhowe** [comment]
Need to be careful with timing here (short-term)... and think about how to make it adaptable to different reading rates (long-term)

Assigning to @billposters for testing
