### ISSUE TITLE
Buttons on slider pages should start 'disabled'

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#167]
For all pages with sliders and buttons, the buttons need to be disabled until the slider is moved (this primarily refers to all the quiz questions). It should be impossible to simply accept the default by clicking 'next'.

**Comment by aaronalbinson** [comment]
Merged into master, could it be checked on touchscreen please @billposters

**Comment by dhowe** [comment]
Absolutely. Thanks

**Comment by billposters** [comment]
Will verify today when we setup the PIs in the installation! Thanks for all the hard work!
