### ISSUE TITLE
Full set of shallow-fake target videos

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#171]
on-hold pending further conversation

**Comment by billposters** [comment]
We need to put an offer together for HAo Li if we want them to provide this service.

**Comment by dhowe** [comment]
yes, in his last two emails he seemed quite open to this... if we can do it without crazy complexity, I think it is a huge win for the installation --- and is something that people might actually want to share with friends

we need to ask him a) what his technical requirements would be, and b) what, in addition to credit and notoriety, would we want in return...

**Comment by billposters** [comment]
Agree. I'll chase him now and update this ticket asap...

**Comment by billposters** [comment]
have chased today! Will update asap
