### ISSUE TITLE
Design for post-experience pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#174]

**Comment by billposters** [comment]
Do we have a designer for this type of work yet? i think you mentioned you had someone in mind @dhowe ?

**Comment by dhowe** [comment]
Not yet. I've made several inquiries, but nothing has materialized. I will follow up...

for the search engine: 'we need to hire a designer'

**Comment by billposters** [comment]
I'm speaking with tactical tech on Weds this week and will ask then to collate content ideas and copy for the IRL section of the post experience. I will make sure it links to the tech and techniques that Spectre is subverting so it all makes sense when displayed after 'how spectre took your data' etc. This can then be fed direct to designer.

**Comment by billposters** [comment]
Can we get raymond on this post-review of his initial work?

**Comment by billposters** [comment]
Content proposal: 

1 scrolling page with the post-experience content structured in 4 parts: 

- how spectre took your data and which tech and techniques were involved at each stage of the UX
 - how this changed the users experience (content that was personalised - users to select from, dark ad task etc)
- how similar tech and techniques are used in IRL. (content from tactical tech). 
- links to open source privacy tools (tactical tech)

**Comment by dhowe** [comment]
perhaps add these to my recent version of the design brief?

**Comment by billposters** [comment]
Is the document in the drive? can only see my v1 draft

**Comment by dhowe** [comment]
its in the drive and in email

**Comment by billposters** [comment]
UPDATE: 
- tactical tech want to partner for the post experience IRL content 
- If we give them a list of techniques, technologies, methods that Spectre simulates and we want to explore, they will collate video, text and infographic content to our specs. 

Collated a proposed first list of content to explore in the post experience page (this list follows the use of the methods in the UX from start to finish): 

**Section 1** 
What Spectre did and How: 

1 - TOS (DARK DESIGN PATTERNS / Single task design philosophy etc)

2 - USER SELFIE  / BIOMETRIC DATA, how this is used in irl? //Tactical tech have a great infographic entitled 'Life of A Selfie' that could be used here as part of content) 

3 - PERSONALISATION (Generative language, behavioural profiling etc)

4 - GAMIFICATION (rewards, addiction, manipulation)

5 - OCEAN PSYCHOMETRIC PROFILING 

6 - MICRO-TARGETTING / DARK ADS

7 - SYNTHESISED VIDEO (deep fake tech / shallow fake tech if possible to include etc)


**Section 2 - How these tech, techniques etc are used in the real world:** 

1 - Corporate spehere
* tactical tech's 'data and politics' team collate this information to match content above

2 - Political Sphere 
* tactical tech's 'data and politics' team collate this information to match content above

**Section 3 - Fight Back /  Privacy Tools:** 

- List / link to tactical tech's 'data detox kit' (or similar)

**Comment by billposters** [comment]
> perhaps add these to my recent version of the design brief?

think we need to develop this content further before adding to design brief

**Comment by dhowe** [comment]
This is a great start. But this is a big chunk of work, and one that needs to be tight or could have a net negative effect. 

I think perhaps we need a sort of two-pronged attack where we a) integrate/verify some of these aspects more specifically into the experience design, and then b) add their explanation to the post-experience.

Have you talked with our designer about increasing the level of dark-patterns, gamification, etc. ? This should be in the design spec

**Comment by billposters** [comment]
increasing dark patterns / gamification might not be necessary. We use examples of dark patterns ie. single task design, tos. These could be enough to start a survey of techniques in the post experience that are used in the real world - we don't need to use every technique / example. 

Gamification is already running throughout several aspects of the UX. How much more is needed to validate explanation of other examples ie. addiction, gambling techniques etc. in the post experience part? 

I feel reluctant to add more to the design brief as we have 1 week to get finished design templates to then build in the FE prior to testing. 1 week is not a long time. 

How many weeks / days will it take a FE dev / yourself and Kenny to build the final FE pages of the app? Once we can understand the workload already, we could look at tweaking parts of the UX but as mentioned, I'm reluctant to do this given time constraints and our multi-user testing concerns.

Spectre is a strong experience for audiences, the prototype (!!) blew people away in sheffield.

**Comment by billposters** [comment]
Also worth clarifying - we would give the list of techniques / technologies we want to explore in the post experience section to Tactical Tech's Data & Politics team, we say what kind of asssets we need (video to embed, infographic, 150 words here etc,) and they would provide the content for us to apply to the page. 

The automated elements would need to be BE which is more work for you though. For example, {username]'s OCEAN profile etc

**Comment by dhowe** [comment]
I hear your point about time-frame, but I was thinking that this might happen post Feb in conjunction with testing in manchester... 

 from my perspective we are not hitting dark design or gamification nearly hard enough to sell the 'look what we did to you and how we did it...' 

> Spectre is a strong experience for audiences, the prototype (!!) blew people away in sheffield

its important to remember that we have no real evidence of this -- conversations you and I had with people who knew we were the artists really cannot be counted, and not to let it keep us from noting weak spots and/or places for improvement

**Comment by dhowe** [comment]
Two key questions ported over from tg:
1. Will the post-experience website need access to the user database ?
1. Does the post-experience website need to be running during the exhibition ?

**Comment by billposters** [comment]
1 - no idea not my area of knowledge
2 - I would say yes to this if people check their emails shortly after fnishng UX

**Comment by dhowe** [comment]
> 1 - no idea not my area of knowledge

I will rephrase: does the content need access to data from the users spectre experience (e.g., their OCEAN profile) ?

> 2 - I would say yes to this if people check their emails shortly after fnishng UX

We can, of course, send the emails whenever we want

**Comment by billposters** [comment]
> > 1 - no idea not my area of knowledge
> 
> I will rephrase: does the post-experience content need to reference data from the users spectre experience (e.g., their OCEAN profile, or their chosen virtue) ?

- I would of said yes to this. So we can show their ocean profile, the personality profile text that was created. 

- Would also be good to show their dark ad that they created and relate to IRL info too
> 
> > 2 - I would say yes to this if people check their emails shortly after fnishng UX
> 
> We can send the emails whenever we like...
- yes true, can you scope out both options and then we can make a decision?

**Comment by billposters** [comment]
> > 1 - no idea not my area of knowledge
> 
> I will rephrase: does the post-experience content need to reference data from the users spectre experience (e.g., their OCEAN profile, or their chosen virtue) ?
> Ok then yes, for OCEAN infographic and text. Yes for dark ad too, so they can see it in relation to other examples / content that Tactical tech provide 

> > 2 - I would say yes to this if people check their emails shortly after fnishng UX
> 
> We can send the emails whenever we like...
- true, can you scope both in terms of what is involved and then we can make a decision? Would we send all users from Day 1  an email when the installation is shut down for the night? DOn't know how this would work so please do let me know how both options could work

**Comment by dhowe** [comment]
>         1 - no idea not my area of knowledge
> 
>     I will rephrase: does the post-experience content need to reference data from the users spectre experience (e.g., their OCEAN profile, or their chosen virtue) ?
> 
>     Ok then yes, for OCEAN infographic and text. Yes for dark ad too, so they can see it in relation to other examples / content that Tactical tech provide
> 
>         2 - I would say yes to this if people check their emails shortly after fnishng UX
> 
>     We can send the emails whenever we like...
> 
>     true, can you scope both in terms of what is involved and then we can make a decision? Would we send all users from Day 1 an email when the installation is shut down for the night? DOn't know how this would work so please do let me know how both options could work
>

**Comment by billposters** [comment]
ok we should look at sending emails all at once if that is easier. 
One thing we may miss though is people checking their email a little after the experience, finding the email from Spectre and checking the post ex and telling their friends about it during the same day etc...

**Comment by billposters** [comment]
Here is the current framework for content in the post-experience page; 


**Section 1 - What Spectre did and how:**

**1 - TOS** (dark design patterns etc)

**2 - USER SELFIE / BIOMETRIC DATA** (Tactical tech have a great infographic entitled 'Life of A Selfie' that could be used to illustrate issues as part of content in Section 2)

**3 - PERSONALISATION** (Generative language, behavioural profiling, cookies and local storage)

**4 - GAMIFICATION** (rewards, addiction, manipulation, Single task design philosophy etc)

**5 - OCEAN PSYCHOMETRIC PROFILING**

**6 - MICRO-TARGETING / DARK ADS**

**7 - SYNTHESISED VIDEO** (synthesised video (deep fake tech / shallow fake tech))

**Section 2 - How these technologies, techniques and methods etc are used in the real world:**

- 100 to 150 words of written text for each 7 categories.

- Relevany video / animation content that is pre-existing from previous Data & Politics work for each category

- an infographic (if available) for each category

Applied to the following contexts:

**1 - Corporate sphere**

tactical tech's 'data and politics' team collate this information to match content above

**2 - Political Sphere**

tactical tech's 'data and politics' team collate this information to match content above

**Section 3 - Fight Back / Privacy Tools:**

List / link to tactical tech's 'data detox kit' here (or similar)

**Comment by dhowe** [comment]
Will need design for this page or pages

**Comment by dhowe** [comment]
See also https://github.com/dhowe/spectre/issues/176

**Comment by billposters** [comment]
> Will need design for this page or pages, including the login interface that people see when they click the link on the email (or the email could login them in automatically).
> 
> @billposters There are security/privacy concerns to consider here as well, especially if we are displaying user data, since (as yet) there is no password or other means to verify that the person who is visiting the site is the same person who did the installation.
> 
> For example if I am stalking person X and know they did the installation, I simply use their email account to login to the post-experience site...
> 
> creating a separate ticket for this (#443)

really good point Dan. We will have to check however it is a US installation and they don't have anything like GDPR! 

what do you think about logging them in automatically? Would this be easier to do from your end? happy to use any system or approach that lightens your workload.

**Comment by billposters** [comment]
Urgent - @dhowe, should sections 1 and 2 above be combined into 1 section? What Spectre did / what Spectre learned about a user, followed by real world examples? 

I can't quite see the benefit of splitting the first 2 sections into seperate components for the web page design now that i am finalising the desing brief. What are your thoughts?

**Comment by dhowe** [comment]
Makes sense. "Spectre did X and Y. This is similar to what happens online when you visit..."

**Comment by billposters** [comment]
yeah i think so too, then the user will grasp each technique / technology better I think.

**Comment by dhowe** [comment]
great work @peterbix 
opening a new ticket for feedback:  #551
