### ISSUE TITLE
Design for SPECTRE web home page

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#176]

**Comment by billposters** [comment]
Can we get Raymond on this once we review his work after a few initial tasks?

**Comment by billposters** [comment]
Initial design proposal: 
- background image of Spectre full page (https://drive.google.com/drive/folders/1RM1VnS3Sj9tMjCIPzXpOfgTBr5Ox9heZ)
- small centrally located box,  'login: enter your email address'
- next page is 1 scrolling page with the post-experience content structured in 4 parts: 
1 - how spectre took your data and which tech and techniques were involved at each stage of the UX
2 - how this changed the users experience (content that was personalised - users to select from, dark ad task etc)
3 - how similar tech and techniques are used in IRL. (content from tactical tech). 
4 - links to open source privacy tools (tactical tech)

**Comment by dhowe** [comment]
do users come to this from the installation or from the email, or both? 
again, we already have their email... is this to find their data from the installation?
what if they haven't done, or haven't finished the installation ?

**Comment by billposters** [comment]
From email only I think, what do you think? 
Good point re finishing the install, perhaps 2 user email logs could be created in the BE: 
1 - those that finished UX
2 - partial finish 

Could we make the post exp page dynamic so if they only got to page 12, we would show how spectre used their data up to that point? 

Or do we discard those users for not completing in the first place?

**Comment by billposters** [comment]
This conflicts with ticket #189 if we discard the data for those that don't finish the UX.

**Comment by dhowe** [comment]
> This conflicts with ticket #189 if we discard the data for those that don't finish the UX.

Not exactly. #189 is about users leaving and returning to the installation. This ticket is about what users (who make it all the way through) see when they click on the link in the email. But I guess this can be combined with #174 (done).

**Comment by billposters** [comment]
thanks Dan, closed it by accident. Apologies! thanks for combining
