### ISSUE TITLE
Specification for post-experience emails

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#178]
Must-haves:
* user image (in circle)
* user ocean graphic
* text below (dynamic)
* unique login link

Might-be-nice (could also be in post-experience pages):
* AI-computed user age/gender
* Facial landmarks over user image
* Others' ratings of this user (averaged slider-values)
* Note about how you have been targeting similar users to yourself

**Comment by billposters** [comment]
would be great to decide on content this coming week if possible.

**Comment by billposters** [comment]
I'm speaking with tactical tech on Weds this week and will ask then to collate content ideas and copy for the IRL section of the post experience. I will make sure it links to the tech and techniques that Spectre is subverting so it all makes sense when displayed after 'how spectre took your data' etc

**Comment by billposters** [comment]
I think content could be structured around; 

- intro sentance (thank you for worshiping at the altar of dataism...)
- Do you think you were really the only one influencing others? 
- Please click on the link below to learn the secrets from the gods of silicon valley, and see how Spectre influenced you during your experience...
- Link to click on that directs them to a simple portal page (Spectre website landing page)
- input your email address and learn the secrets of the digital influence industry!
- share this project with your friends? Social links / hashtags  / pre-defined post content for sharing on FB and twitter

- goodbye... for now!

**Comment by dhowe** [comment]
we don't need their email again, as we have it already... 
are we 100% certain that we will be sending emails? 
if so, we can begin building this technical component, even without the content

**Comment by billposters** [comment]
Proposed email login was just for verification purposes on the website. 
yea I think it makes sense. To do it in private later on etc...

**Comment by dhowe** [comment]
As I've argued before, this is only worth doing if what we're telling them really is SURPRISING or UNEXPECTED. 

"Click on the link below to learn the secrets from the gods of silicon valley, and see how Spectre influenced you during your experience..."

The worst case is that they go through the hassle of relogging in and then are bored or told things they already know, and feel their time was wasted... The only people who will do it already feel positive about the experience, so the risk is bigger. 

And, as it is, we are not doing very much in terms of personalisation, compared to what your average site does online.  I think the shallow-fake component could be powerful here, including an explainer of how it works, along with the brand game... but without the former I'm not sure the payoff justifies the work/risk

**Comment by billposters** [comment]
Dear [username], 

- intro sentence / thank user for their data and for joining a congregation of billions.

- Your psychometric profile is attached to this email for future reference (or something).

- Spectre is always excited to welcome new followers who are: X, Y, Z (ocean text here)

- Share your psychological profile with your friends online? (pre-filled social post for facebook or twitter as a provocation) [SHARE POST?]

- If you feel unsure about making this private information public, you are right to be concerned. Click on the link below to reveal the secrets of the digital influence industry and find out more about why privacy matters... [CLICK] (link to spectre website to view their personal post experience page)

**Comment by dhowe** [comment]
Backend tech for this is underway, currently wrangling with issues around the conversion of react templates to straight html with inline css (will also have to deal with images)

**Comment by billposters** [comment]
Ok good work! Keep on it!

**Comment by billposters** [comment]
We could also explore including what other users' thought of them when they answered slider questions etc

**Comment by dhowe** [comment]
> We could also explore including what other users' thought of them when they answered slider questions etc

as well as what our AI assessed their gender and age as ... ?

**Comment by dhowe** [comment]
creating a separate ticket for feedback on @peterbix new email design (see #489)
