### ISSUE TITLE
Validation of email field on Login Page

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#180]
- [x] Email validation [there is a function already there which can be used or not]
- [x] If email is invalid, show overlay saying 'Please enter a valid email.'
- [ ] if user already exists in db, show overlay, saying 'Sorry, it looks like you've already visited Spectre. You can try again tomorrow.'

**Comment by billposters** [comment]
Yes agree. They should be faded out, 50% transparency or something
similar until an action happens ie. move a slider.

We can remove many on the text screens that fade in and fade out.

B

On 28/05/2019 19:51, Daniel Howe wrote:
> Email (valid email format), Name, etc.
>
> I think we should also remove lots of the skip/next buttons (or have them disabled until a choice is entered) -- do you agree @billposters ?
>
-- 
Barney Francis

Honorary Research Fellow  
School of Arts, Languages and Cultures
University of Manchester

http://www.billposters.ch

**Comment by dhowe** [comment]
I've added a function to validate emails, please integrate it and use an overlay if it is not valid

**Comment by yosser** [comment]
How do I know if a user already exists in the DB?  What form should the overlay take (do we have an existing library we use for this?)

**Comment by dhowe** [comment]
1. That involves communicating with the DB, but perhaps you can fake it for now?
2. @joseph-allen says: 
> we're using material ui for components which has modal component
> https://material-ui.com/api/modal/

**Comment by dhowe** [comment]
@yosser did you say you'd pushed a change for this?

**Comment by yosser** [comment]
This should be working now.  There's a fake Api error test for duplicate emails in LoginPage.jsx line 49

**Comment by dhowe** [comment]
on-hold for re-integration of back-end
