### ISSUE TITLE
Plan for users leaving/returning 

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#189]

**Comment by joseph-allen** [comment]
no details here, this isn't a ticket for devs?

**Comment by dhowe** [comment]
this is on the 'assets' board, so no dev yet

**Comment by dhowe** [comment]
Two options here:
1. simple/ugly - don't let users relogin with the same email (they can use a different email and rerun the whole thing). Required:  a login 'reject' page when email is the same
2. better/more-complex - allow users to relogin and return them to the last page they visited before leaving. Required: tracking last page

**Comment by billposters** [comment]
Thanks for this Dan, how much work (roughly) is required time wise for
option 2?

B

On 30/05/2019 18:54, Daniel Howe wrote:
> Two options here:
> 1. simple/ugly - don't let users relogin with the same email (they can use a different email and rerun the whole thing). Required:  a login 'reject' page when email is the same
> 2. better/more-complex - allow users to relogin and return them to the last page they visited before leaving. Required: tracking last page
>
-- 
Barney Francis

Honorary Research Fellow  
School of Arts, Languages and Cultures
University of Manchester

http://www.billposters.ch

**Comment by billposters** [comment]
I think a time out is a good idea with the option to login again as long as it's not too much work on your side

**Comment by dhowe** [comment]
so what happens to their previous database record -- it is overwritten?

**Comment by billposters** [comment]
I don't know what is best to do, I am unfamiliar with BE processes. If it's easier to not give the option then lets not. Saves a fair bit of time etc. and i think people will stick with the UX but that's just an assumption based on users during sheffield

**Comment by dhowe** [comment]
This is a UX question -- we have a user that has logged in and done at least some # of pages, ( possibly even finished the whole thing). Then they come back and want to do it again. 

Users records are keyed on email, so they cannot create a brand new record. But we can bring them to the page they last were on, with the data they had previously amassed. Or we can refuse them access, so that they have to create a new email or go away. 

Those are basically the two options -- first is better but more work, second is easier but frustrating, plus we  potentially get lots of fake emails...

**Comment by billposters** [comment]
Yes I agree the fake emails question is a pertinent one, especially in relation to post-exp access.
We should go for Option 1 (can return to last page completed) and add a written prompt when they are on the login page at the start of the UX to use a correct email address to get the 'full experience'. what do you think?

**Comment by dhowe** [comment]
see also #443
