### ISSUE TITLE
LoginPage page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#196]
- [x] Merge with Username #198 / See new design spec below 
- [x] Play SpectreIntro.mp4 video when submit button is pressed, then go to next page
- [x] Input for email needs to be longer as characters now disappear
- [x] Check keyboard inc. shift / caps / delete etc
- [x] Email validation: there is a validation function that looks for email-like things:/*@*.*/ - If it fails there is a modal that pops up saying 'Oops, etc'. Close and try again. 3 tries and you get in automatically.
- [x] When email is rejected, must clear the email text field, but not the others
- [x] Error handling: must _always_ be able to get through this page

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/58712508-99db0680-83b8-11e9-9346-d86c2bf8c3f6.png)

**Comment by dhowe** [comment]
@billposters need intro video link here

**Comment by billposters** [comment]
INTRO-VIDEO download link: 

https://wetransfer.com/downloads/5197b0ecd8d1007d5a88378270ee433d20190602190033/4cbb674952f33632d8e0444e860ddd4120190602190033/4e3416

**Comment by dhowe** [comment]
@pauljervis we need to get the video above into github, then get it playing in an overlay when the user hits next. This overlay component (1320x1080) should have a black background and video should be centered. This component will be re-used in at least 2-3 other locations

**Comment by pauljervis** [comment]
- Videos may be different sizes so auto-centre
- Play immediately and then progress after completion (callback in component?)

**Comment by billposters** [comment]
@pauljervis - please can you move the video auto load so it plays after #198 instead of this page? We tested it would be much better if it played when the user clicks 'begin at the end of the  'username' page

**Comment by billposters** [comment]
Design Spec: 

![Login_Page_design_spec](https://user-images.githubusercontent.com/48989022/58925411-575e5480-873f-11e9-9cc4-f907b8ed9270.jpg)
