### ISSUE TITLE
Username page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#198]
- [ ] Centre name text field on screen
- [ ] When 'begin' pressed, 'Intro-Video' loads as overlay (see note below)

** this video needs moving from LoginPage to this one please!

Note: When 'begin' is pressed video overlay should open and video should autostart. Videos may be different sizes so should be auto-centered. When video ends go immediately to next page (/pledge)

**Comment by billposters** [comment]
**This is how the page looks now:** 
![IMG_9310](https://user-images.githubusercontent.com/48989022/58748065-702ee780-846b-11e9-97dc-f9124d1d5f1a.JPG)

**Comment by billposters** [comment]
![IMG_9622](https://user-images.githubusercontent.com/48989022/58825651-d451d700-8636-11e9-9475-5193e273e7a8.JPG)
