### ISSUE TITLE
CircleCI Building Tests

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#2]
Get CircleCI to correctly build tests in the subdirectory.

**Comment by dhowe** [comment]
and stop attempting to build the root (I get fail messages from circleci on every push )

**Comment by joseph-allen** [comment]
apologies, will be resolved soon!

**Comment by joseph-allen** [comment]
i'll merge a branch that doesn't attempt to do anything other than install the packages to resolve this for now

**Comment by dhowe** [comment]
no worries -- i have a filter
