### ISSUE TITLE
Pledge page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#200]
- [x] Check interstitial timings and ensure each sentence appears in 2 second intervals
- [x] Remove visible countdown timer
- [x] adjust line spacing (see screenshot & design spec below)

**Comment by billposters** [comment]
Screen capture as it is now: 
![IMG_9511](https://user-images.githubusercontent.com/48989022/58748164-635ec380-846c-11e9-811f-5d368d789dd7.JPG)

**Comment by billposters** [comment]
Design spec: 

![Pledge_Design_Spec](https://user-images.githubusercontent.com/48989022/58755827-e707c700-84e3-11e9-8e01-5d9d27852923.jpg)

**Comment by pauljervis** [comment]
@dhowe @billposters can I confirm the User Journey on this page? From what I see, they enter the page, the first paragraph loads immediately, then two seconds after it completes, the second loads, then two seconds after that completes the third loads.

After that, how does the user progress to the next page? In the code there is a button that has just been hidden so am I revealing that two seconds after the third paragraph or am I automatically progressing them after a set period of time (I assume two seconds after the third paragraph)

**Comment by billposters** [comment]
@pauljervis - yes please reveal theg button on the page after the last text has loaded. I think 2 secs per line is ok but we may need to revist.

**Comment by billposters** [comment]
Hi @pauljervis , one last change needed to this page and then it is done! 

- need the line spacings sorting as in design spec.

Here is the screenshot: 

![IMG_9586](https://user-images.githubusercontent.com/48989022/58766288-a5732c80-8574-11e9-8594-8abb4a0fbf35.JPG)
