### ISSUE TITLE
SearchingFor page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#201]
- [x] adjust line spacing and centre all content like on design spec
- [x] when pressed, Insight and wealth are switched at present. If you press insight - the next page loads 'wealth' as the virtue insted. Same vice versa. 
- [x] Please fix warnings in console:
![Screen Shot 2019-06-02 at 2 09 01 PM](https://user-images.githubusercontent.com/737638/58761833-409ddf00-8540-11e9-874d-c8c449341954.png)

**Comment by billposters** [comment]
Page as it looks now: 
![IMG_1449](https://user-images.githubusercontent.com/48989022/58748239-876ed480-846d-11e9-8a92-d85914c0dd8d.JPG)

**Comment by billposters** [comment]
Design Spec: 

![SearchingFor_Design_spec_1080_by_1920](https://user-images.githubusercontent.com/48989022/58752849-b7d66300-84ad-11e9-9116-f9940321ab60.jpg)

**Comment by billposters** [comment]
Design assets - button SVG, Ai file, design spec: 

https://we.tl/t-T672X2VF4H

**Comment by cqx931** [comment]
The font-size for the buttons doesn't look like 44px. I used 28px to fit into the buttons.

**Comment by cqx931** [comment]
I didn't use the button SVG for this one, as there is only one single svg file and multiple buttons. I took reference of the font-size in the design file and set the font-size of the buttons to be 30px instead of 44px.

**Comment by billposters** [comment]
Design spec updated: 

![SearchingFor_Design_spec_FINAL](https://user-images.githubusercontent.com/48989022/58766351-714c3b80-8575-11e9-8512-b4290af46e88.jpg)

**Comment by billposters** [comment]
Screenshot:

![IMG_4119](https://user-images.githubusercontent.com/48989022/58766357-81641b00-8575-11e9-809a-74ae1f8f8956.JPG)
