### ISSUE TITLE
DataIs page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#202]
- [x] Create Interstitial timing (2 seconds per line)
- [x]  Hide the countdown timer . should be invisible
- [x] sort the line spacing to match design spec

**Comment by billposters** [comment]
Screenshot: 
![IMG_8003](https://user-images.githubusercontent.com/48989022/58748366-8dfe4b80-846f-11e9-98fb-f23dd5b2fe14.JPG)

**Comment by billposters** [comment]
No other text loads up before the page times out.

**Comment by billposters** [comment]
Design Spec: 

![Data_Is_Design_Spec](https://user-images.githubusercontent.com/48989022/58755247-b9b51c00-84d7-11e9-9b59-4445d3e36d30.jpg)
