### ISSUE TITLE
PersonalisedExperience page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#203]
- [x] add interstitials, 1 second per line of text
- [x] remove ‘excellent’ text from page 
- [x] format text and line spacing to design spec criteria

**Comment by billposters** [comment]
![IMG_1630](https://user-images.githubusercontent.com/48989022/58748417-56dc6a00-8470-11e9-8b97-4cd4ed4b8670.JPG)

**Comment by billposters** [comment]
Design Spec: 

![PersonalisedExperience_Design_Spec](https://user-images.githubusercontent.com/48989022/58755340-a4d98800-84d9-11e9-8923-ca2f459a38b9.jpg)

**Comment by billposters** [comment]
Button component is style as one used in #222
