### ISSUE TITLE
Game page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#204]
- [x] Create pop up instruction graphic that opens as soon as page loads (see graphic below). Animation starts when user clicks play button
- [x] Add 'Love' text above the top grey line, add 'Hate' below the last grey line. Font size = 48, centred, semi bold. style sheet blue.
- [x] Remove FPS counter from top left

**Comment by billposters** [comment]
![Game_pop_up_instruction_box_614px_by_324px](https://user-images.githubusercontent.com/48989022/58748790-6c07c780-8475-11e9-8aac-b357b7911909.png)

**Comment by billposters** [comment]
Screen shot as it looks now: 

 ![IMG_5617](https://user-images.githubusercontent.com/48989022/58748822-b25d2680-8475-11e9-8b70-2ee6b4d8575a.JPG)
