### ISSUE TITLE
ThankYou page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#205]
@aaronalbinson - final spec: 
- [x] format text and line spacing to match design criteria (see below)
- [x] add thumbs up icon
- [x] Keep the 'Next button that is on the page already in the same place, same style.

**Comment by billposters** [comment]
Design Spec: 

![ThankYou_Design_Spec](https://user-images.githubusercontent.com/48989022/58755441-161a3a80-84dc-11e9-9a5b-4394d36fa1c2.jpg)
