### ISSUE TITLE
SelectedAvatar page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#208]
- [x] adjust line spacing to match spec below 
- [x] name of follower needs to be located closer to profile pic (large gap between each element at present

**Comment by billposters** [comment]
Design Spec: 

![SelectedAvatar_Design_Spec](https://user-images.githubusercontent.com/48989022/58755923-b1fc7400-84e5-11e9-8cfe-49da883b79d1.jpg)

**Comment by billposters** [comment]
Screenshot: 

- needs line spacing adjusting a little bit and that is all!

![IMG_5275](https://user-images.githubusercontent.com/48989022/58766541-d56fff00-8577-11e9-8d28-82f6db41643e.JPG)
