### ISSUE TITLE
InsightGender  page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#209]
- [ ] Needs to display [username] in question text. 

**_The above needs to be applied to ALL all Insight pages_**

**Comment by billposters** [comment]
Design Spec: 

![Insight_gender_design_spec](https://user-images.githubusercontent.com/48989022/58754151-51a80b00-84c2-11e9-9e44-d4c0f7c9ad25.jpg)

**Comment by billposters** [comment]
SLIDER object: 

[Insight_slider_object.pdf](https://github.com/dhowe/spectre/files/3244245/Insight_slider_object.pdf)

**Comment by billposters** [comment]
![Insight_slider_design_spec](https://user-images.githubusercontent.com/48989022/58754223-8ff1fa00-84c3-11e9-9d1e-2a2ddc9a4332.jpg)

**Comment by billposters** [comment]
Slider object: 
[Insight_slider_object.pdf](https://github.com/dhowe/spectre/files/3244251/Insight_slider_object.pdf)

**Comment by cqx931** [comment]
Implemented the slider but didn't figure out a way to implement the same 30px gap between the slider and the text on both sides.

**Comment by billposters** [comment]
@cqx931 

Screenshot: 

![IMG_1364](https://user-images.githubusercontent.com/48989022/58766561-38fa2c80-8578-11e9-98be-978fe23177bf.JPG)
