### ISSUE TITLE
InsightSkin page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#210]
same as InsightGender #209

- [ ] needs profile pic display fixing

**Comment by billposters** [comment]
![Insight_skin_design_spec](https://user-images.githubusercontent.com/48989022/58754194-0e9a6780-84c3-11e9-952f-39a313401ff0.jpg)

**Comment by billposters** [comment]
@cqx931 
screenshot: 

![IMG_3516](https://user-images.githubusercontent.com/48989022/58766614-8f676b00-8578-11e9-83e0-93d1c5fd8d51.JPG)
