### ISSUE TITLE
InsightThankYou page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#212]
- [x] implement redesign below (spec and asset below)

- [x] icon needs aligning centrally
- [ ] line spacing adjusting and font weight / text layout adjusting

**Comment by billposters** [comment]
Thumbs up icon 

[Thumbs_Up_Icon.pdf](https://github.com/dhowe/spectre/files/3244222/Thumbs_Up_Icon.pdf)

SVG File (200px x 200px:

https://we.tl/t-IvkbkGbo54

**Comment by billposters** [comment]
![Insight_Thankyou_design_spec](https://user-images.githubusercontent.com/48989022/58754332-a39e6000-84c5-11e9-8670-7411553d97a7.jpg)

**Comment by billposters** [comment]
Lets go deeper button: 

SVG:  https://we.tl/t-c3D5OaoUum

PDF: 
[Lets_go_deeper_button.pdf](https://github.com/dhowe/spectre/files/3244264/Lets_go_deeper_button.pdf)

**Comment by billposters** [comment]
@pauljervis 
Screenshot: 

![IMG_8012](https://user-images.githubusercontent.com/48989022/58766638-df463200-8578-11e9-8594-e200da5edfa6.JPG)
