### ISSUE TITLE
InsightSexuality page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#213]
same as InsightGender #209

**Comment by billposters** [comment]
![InsightSexuality_Design_Spec](https://user-images.githubusercontent.com/48989022/58754734-d39e3100-84ce-11e9-9588-845fe67ba7bf.jpg)

**Comment by billposters** [comment]
@cqx931 

Screen shot:

![IMG_2673](https://user-images.githubusercontent.com/48989022/58766723-b4101280-8579-11e9-978d-ca7c798b1452.JPG)
