### ISSUE TITLE
InsightPolitical page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#214]
- [ ] 'right wing' text needs to be on one line only. Maybe adjust font size for all slider labels?
see #158

**Comment by billposters** [comment]
![Insight_Political_design_spec](https://user-images.githubusercontent.com/48989022/58754768-75258280-84cf-11e9-8658-bb5bc492d717.jpg)

**Comment by cqx931** [comment]
"Right wing" is slightly wider than the allocated width in what I implemented. This still need to be fixed.

![image](https://user-images.githubusercontent.com/3056154/58756758-dac43f80-84cc-11e9-9a14-d72850c83a96.png)

**Comment by billposters** [comment]
screenshot:

![IMG_3343](https://user-images.githubusercontent.com/48989022/58766743-005b5280-857a-11e9-8fe3-75cf6d1e45b3.JPG)
