### ISSUE TITLE
InsightComplete page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#215]
- [x] Ocean profile component needs removing from this page  
- [x] 'Intro_To_Ocean' video linked to the 'Play' icon & 'WTF is OCEAN?' button (video ready Weds am)
- [x] After video plays. next page loads = YourPower

Video:
/public/video/IntroToOcean

**Comment by billposters** [comment]
![Insight_Complete_mockup](https://user-images.githubusercontent.com/48989022/58672450-e1bd4780-833e-11e9-904a-2dc437b66334.jpg)

**Comment by billposters** [comment]
[OCEAN_Top_bar_450px_by_1080px.pdf](https://github.com/dhowe/spectre/files/3243139/OCEAN_Top_bar_450px_by_1080px.pdf)

**Comment by billposters** [comment]
Screenshot
![IMG_5526](https://user-images.githubusercontent.com/48989022/58767208-2126a680-8580-11e9-965b-f7d5f78a9a63.JPG)
