### ISSUE TITLE
YourPower page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#216]
- [x] Remove OCEAN top bar header and replace with previous / normal header (ensure number 1 is active)
- [ ] Check interstitials 
- [x] Remove header (OCEAN profile bar) and replace with standard header /

**Comment by billposters** [comment]
![IMG_8540](https://user-images.githubusercontent.com/48989022/58767887-98146d00-8589-11e9-9176-99ba8ec1aaf5.JPG)
