### ISSUE TITLE
Campaign page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#218]
- [ ] Remove OCEAN top bar and insert previous header (ensure number 1 is active)
- [ ] needs text adding to page. See page spec below.

Text: 
Let’s use a simple design tool 
to create  a targetted Facebook ad.

[Username’s] OCEAN profile shows
that [he] is influenced by: ]

Images that contain X and Y

Slogans that contain X and Y

Influence Them!

**Comment by billposters** [comment]
Design Spec: 

![Campaign_design_spec](https://user-images.githubusercontent.com/48989022/58902207-90c0a100-86fa-11e9-86f8-57f58104a435.jpg)
