### ISSUE TITLE
DarkAd page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#219]
- [ ] Remove the 'line break' characters that are visible in the  'Hate the EU. Love Europe' slogan
- [ ] Remove OCEAN top bar and insert previous header (ensure number 1 is active) (same as #216 #217 #218

**Comment by billposters** [comment]
![DESIGN_TOOL_MOCKUP](https://user-images.githubusercontent.com/48989022/58663338-30111d00-8324-11e9-90f1-bf7f011ac7d8.jpg)

**Comment by billposters** [comment]
[Dark_Ad_landing_page.pdf](https://github.com/dhowe/spectre/files/3241191/Dark_Ad_landing_page.pdf)

**Comment by billposters** [comment]
[Dark_Ad_Page_Spec_DIMENSIONS.pdf](https://github.com/dhowe/spectre/files/3241193/Dark_Ad_Page_Spec_DIMENSIONS.pdf)

**Comment by billposters** [comment]
![Vote_leave_icon](https://user-images.githubusercontent.com/48989022/58740516-c74fa080-8408-11e9-8720-097915a3fe04.png)

**Comment by billposters** [comment]
![Vote_Remain_icon](https://user-images.githubusercontent.com/48989022/58740532-d1719f00-8408-11e9-8342-e0caae3671c8.png)

**Comment by dhowe** [comment]
these images are now in /public/imgs as vote-leave.png and vote-remain.png

**Comment by billposters** [comment]
![Dark_Ad_design_spec_FINAL](https://user-images.githubusercontent.com/48989022/58749216-24843a00-847b-11e9-9015-bb6c47f04da7.jpg)

**Comment by billposters** [comment]
With guides: 

![DarkAd_design_spec_final_with_guides](https://user-images.githubusercontent.com/48989022/58749229-467dbc80-847b-11e9-8c39-7c41b75e93d4.jpg)

**Comment by billposters** [comment]
![What_no_propaganda_placeholder](https://user-images.githubusercontent.com/48989022/58749313-74173580-847c-11e9-85ed-3e8f39bc6138.jpg)

**Comment by joseph-allen** [comment]
still pending layout and placeholder graphic
https://github.com/dhowe/spectre/pull/261

**Comment by joseph-allen** [comment]
"need to handle case where slogan is selected first" we could hide the slogans until an image is selected? open to other ideas

**Comment by joseph-allen** [comment]
replacing the placeholder graphic doesn't have any benefit as long it's a decent resolution image, ready for review

**Comment by billposters** [comment]
@joseph-allen 

Screenshot: 

![IMG_0047](https://user-images.githubusercontent.com/48989022/58767949-b7f86080-858a-11e9-9436-f2749cbd6ee8.JPG)

**Comment by billposters** [comment]
NEW OCEAN PROFILE BAR DESIGN: 

Dimensions = 300 x 1080 
** We had to change the dimensions due to the current profile bar being too heavy for the top of the screen. 

Should be able to reuse all previous components made for this one. 



![OCEAN_Profile_Bar_300_x_1080](https://user-images.githubusercontent.com/48989022/58767983-8b911400-858b-11e9-8f96-be9d847a0aec.jpg)

**Comment by billposters** [comment]
@aaronalbinson - updated tasks

**Comment by aaronalbinson** [comment]
I've completed all tasks on here apart from `Remove the 'line break' characters that are visible in the 'Hate the EU. Love Europe' slogan`

I don't know where this data is being pulled in from and not sure the reason for the line breaks in the first place?

Can someone clarify? @dhowe @billposters 

Ta

**Comment by dhowe** [comment]
done
