### ISSUE TITLE
SuccessAd page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#221]
- [x] all content fades in as one interstitial, 7 second duration,  next page autoloads

- [x] Add trophy icon below first like of text (see design spec below)

**Comment by billposters** [comment]
Design Spec: 

![SuccessAd_Desigbn_Spec](https://user-images.githubusercontent.com/48989022/58755539-cfc5db00-84dd-11e9-9f29-d66ea1339be5.jpg)

**Comment by billposters** [comment]
Latest screenshot;
![IMG_3058](https://user-images.githubusercontent.com/48989022/58768046-c21b5e80-858c-11e9-931d-5f941dc4243d.JPG)

**Comment by billposters** [comment]
Trophy Icon: 

[Trophy_Icon_200_x_200.pdf](https://github.com/dhowe/spectre/files/3245301/Trophy_Icon_200_x_200.pdf)
