### ISSUE TITLE
InfluenceANation  page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#222]
- [x] Update to match design spec below
- [x] Adjust line spacings to same as design spec.
- [x] adjust font weight to match design spec
- [x] Change font in 'Get more data' button to standard font

**Comment by billposters** [comment]
![Influence_a_nation_design_spec](https://user-images.githubusercontent.com/48989022/58753854-a1d09e80-84bd-11e9-8f34-7c4b33597378.jpg)

**Comment by billposters** [comment]
'Get more data' button:

SVG:
https://we.tl/t-hXZdAQl8ih

PDF: 
[Get_more_data_button.pdf](https://github.com/dhowe/spectre/files/3244232/Get_more_data_button.pdf)

**Comment by billposters** [comment]
All design assets complete for this page now!

**Comment by billposters** [comment]
@cqx931 

Screen shot: 


![IMG_9288](https://user-images.githubusercontent.com/48989022/58767918-37396480-858a-11e9-96c5-37b0e94911b0.JPG)

**Comment by dhowe** [comment]
@billposters can you clarify what needs to be done here (and whether it should wait for new tablet-based page layout)?
