### ISSUE TITLE
ConsumerData page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#223]
- [x] - Leave only 9 icons / same layout as Political data page / Same layout as #224 

** choose 9 that make the grid of 3 x 3 icons 
** go for easiest / most logical grid of icons

**Comment by dhowe** [comment]
@billposters will provide icons

**Comment by billposters** [comment]
[248_BRA_Spectre_Icon_Suite_v4.pdf](https://github.com/dhowe/spectre/files/3239082/248_BRA_Spectre_Icon_Suite_v4.pdf)

**Comment by billposters** [comment]
![ConsumerData_design_spec_1080_by_1920](https://user-images.githubusercontent.com/48989022/58750597-5b168080-848c-11e9-9d9f-f850fe400c14.jpg)

**Comment by billposters** [comment]
Consumer data icons: 

SVG: https://we.tl/t-BqsidsH2Cl

PDF: 
[Consumer_data_icons.pdf](https://github.com/dhowe/spectre/files/3244235/Consumer_data_icons.pdf)

**Comment by billposters** [comment]
All design assets complete for this page!

**Comment by billposters** [comment]
Design spec with additional dimensions: 

![ConsumerData_design_spec_FINAL](https://user-images.githubusercontent.com/48989022/58766050-0cdbad00-8572-11e9-9c23-a3650b49cf1a.jpg)

**Comment by billposters** [comment]
@aaronalbinson - have added the extra pixel dimensions to the spec above!

**Comment by billposters** [comment]
Here is a screen shot now: 

- Can you make the point size 14px on the labels for the icons
- Adjust the spacings using the pix measurements above

![IMG_8952](https://user-images.githubusercontent.com/48989022/58766122-e23e2400-8572-11e9-90f5-7c5e9d803b76.JPG)

**Comment by billposters** [comment]
@aaronalbinson - added 1 task

**Comment by aaronalbinson** [comment]
Keep the following:

Health
Finance
Biometric
Online search
shopping & mail order
insurance
social media
travel
location

**Comment by dhowe** [comment]
@billposters can you verify this fix and/or clarify what needs to be done?
