### ISSUE TITLE
PoliticalData page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#224]
- [x] Allow multiple-select
- [x] Add next button
- [x] Only enable next when user has selected 3 or more
- [x] Change rollover color to style-sheet blue
- [x] make line spacing adjustment the same as #223 , #225
** Same as #223

**Comment by dhowe** [comment]
@billposters will provide icons

**Comment by billposters** [comment]
DESIGN SPEC:
![PoliticalData_design_spec](https://user-images.githubusercontent.com/48989022/58751949-4642e880-849e-11e9-9dc7-7d745089d165.jpg)

**Comment by billposters** [comment]
Political data icons: 

SVG: https://we.tl/t-GPfyirFsUa

PDF: 
[PoliticalData_icons.pdf](https://github.com/dhowe/spectre/files/3244236/PoliticalData_icons.pdf)

**Comment by billposters** [comment]
@aaronalbinson  - design spec updated: 

![PoliticalData_design_spec_FINAL](https://user-images.githubusercontent.com/48989022/58766231-04847180-8574-11e9-9630-53ba5246b1b7.jpg)

**Comment by billposters** [comment]
@aaronalbinson - screen shot
![IMG_8001](https://user-images.githubusercontent.com/48989022/58766238-16feab00-8574-11e9-8ab1-a83730e2f257.JPG)

**Comment by billposters** [comment]
@aaronalbinson - updated tasks
