### ISSUE TITLE
HomeData page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#225]
- [x] Allow multiple-select
- [x] Add next button
- [x] Only enable next when user has selected 3 or more
- [x] Change rollover color to style-sheet blue
- [x] make line spacing adjustment the same as #223 

** same as #223 , #224

**Comment by dhowe** [comment]
@billposters will provide icons

**Comment by billposters** [comment]
![HomeData_Design_spec_1080_by_1920](https://user-images.githubusercontent.com/48989022/58752609-ebaf8980-84a9-11e9-9d51-599b890ec1e3.jpg)

**Comment by billposters** [comment]
Home Data Icons: 

SVG:  https://we.tl/t-OyBgJnWb63

PDF: 
[HomeData_Icons.pdf](https://github.com/dhowe/spectre/files/3244237/HomeData_Icons.pdf)

**Comment by billposters** [comment]
@aaronalbinson - additional pix dimensions added

![HomeData_Design_spec_FINAL](https://user-images.githubusercontent.com/48989022/58766176-6b555b00-8573-11e9-80b4-5fee6672e3a6.jpg)

**Comment by billposters** [comment]
@aaronalbinson - screen shot of page layout on touchscreen
![IMG_4952](https://user-images.githubusercontent.com/48989022/58766201-b2dbe700-8573-11e9-96ff-4055394a4b2d.JPG)
