### ISSUE TITLE
FindCitizens page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#226]
- [ ] Make font weight regular not semi bold
- [ ] Increase font size of 'find them' button text 
- [ ] make 'Excellent' strong blue instead of grey
- [ ] TargetsFound video needs to replace the video that currently loads and plays as this isn't correct. 
- [ ] TargetsFound animation video needs to load and play on button press

**Comment by billposters** [comment]
Findcitizens animation asset: 

https://we.tl/t-deknOuRuke

**Comment by billposters** [comment]
![Find_Citizens_Design_Spec](https://user-images.githubusercontent.com/48989022/58756005-8d090080-84e7-11e9-810f-1d8911e2ee1d.jpg)

**Comment by dhowe** [comment]
@billposters dont see download link here

**Comment by billposters** [comment]
Correct design Spec: 
![Find_Citizens_Design_Spec_final](https://user-images.githubusercontent.com/48989022/58761892-e5202100-8540-11e9-93b1-085df811d211.jpg)

**Comment by billposters** [comment]
> @billposters dont see download link here

- Sorry, just amended the design to include the 'find them' button. 
- when this is pressed it loads next page with 'targets found' animation

**Comment by billposters** [comment]
Amended design_spec with button: 

![Find_Citizens_Design_Spec_final](https://user-images.githubusercontent.com/48989022/58761907-20225480-8541-11e9-8764-682e57f7f2af.jpg)

**Comment by billposters** [comment]
> @billposters dont see download link here

- Video plays on 'Targets found' page, have added the video DL to the ticket

**Comment by billposters** [comment]
Latest screenshot: 

![IMG_0960](https://user-images.githubusercontent.com/48989022/58768136-2e4a9200-858e-11e9-8a96-db152f2eb354.JPG)

**Comment by billposters** [comment]
Find them button text is too small 

![IMG_4984](https://user-images.githubusercontent.com/48989022/58827529-2e549b80-863b-11e9-875c-161b003de170.JPG)

**Comment by billposters** [comment]
wrong animation is linked to this page @pauljervis , needs the other one linking please. Filename: TargetsFound. 

Here is the updated version of the animation as the previous one had an error: 

https://we.tl/t-2LJGbaT2F5
