### ISSUE TITLE
TargetsFound page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#227]
- [ ] Auto load animation video at 1080 wide x 1320 high dimensions (main screen/active area). Animation is formatted to exact video dimensions already. 
- [ ] Change 'next' button to read 'Launch Campaign'
- [ ] 'Launch Campaign' button starts disabled, becomes enabled when video finishes.

**Comment by dhowe** [comment]
waiting on animation?

**Comment by billposters** [comment]
TARGETSFOUND animation DL: 

https://we.tl/t-lOGL3Pl2Ja

**Comment by billposters** [comment]
@dhowe - added
