### ISSUE TITLE
Win page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#231]
- [ ] Interstitial, same as #221 SuccessAd
- [x] Text should dynamic swap between: 'Believe' and 'BeLeave' based on user.adIssue
- [ ] format text to same as design spec 
- [ ] add Thumbs up icon 

** Aside from text content, this page is identical to #221

**Comment by billposters** [comment]
Design Spec; 
![Win_Design_Spec](https://user-images.githubusercontent.com/48989022/58755614-54fdbf80-84df-11e9-9fff-7fb2517b75bc.jpg)

**Comment by billposters** [comment]
Latest screenshot: 

![IMG_5655](https://user-images.githubusercontent.com/48989022/58768187-00b21880-858f-11e9-8e09-21e7ec058cc4.JPG)
