### ISSUE TITLE
InfluenceACelebrity page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#233]
- [ ] Interstitial (text should appear sequentially using Fade/Countdown components)
- [ ] Add celebrity images in circle (like logo:) use #259 
- [ ] Each can be clicked to view their video (users can watch as many as they like before hitting 'next')
- [ ] Videos should play in an overlay (videos will be 1320x1080 with black border) 
- [ ] 6 celebs load each time : (preference TBC)

** this page is identical in layout to #259 which is almost complete!

^ Celebs are Kardashian, Trump, Freeman, Duchamp, Hirst, Zuckerberg. Images are attached below, order in circle should be randomized.

See #259

**Comment by dhowe** [comment]
@billposters will supply celeb images

**Comment by billposters** [comment]
Design spec: 

![Influence_A_Celebrity_design_spec](https://user-images.githubusercontent.com/48989022/58750012-94e38900-8484-11e9-960e-db506ccaac6f.jpg)

**Comment by billposters** [comment]
PDF Design File: 

[Influence_A_Celebrity_design_spec.pdf](https://github.com/dhowe/spectre/files/3243868/Influence_A_Celebrity_design_spec.pdf)

**Comment by billposters** [comment]
Hi @aaronalbinson - all components, design specs added now. This is good to go! Thankyou!

**Comment by billposters** [comment]
Latest screenshot:

![IMG_2246](https://user-images.githubusercontent.com/48989022/58768229-b8dfc100-858f-11e9-961a-8548abfade4d.JPG)

**Comment by billposters** [comment]
Video assets have been finalised and sent to @dhowe ready for linking
