### ISSUE TITLE
OCEANReveal page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#234]
- [x] no 'next' button needed
- [x] text to be generated by user object, 5 short sentences (array from @dhowe), use placeholder for now

1. A little data and a little tech goes a long way. 
2. We’ve not known you for long, but already we know you are…
3. Ocean contributor 1 text here
4. Ocean contributor 2 text here
5. Ocean contributor 3 text here

- [x] Each sentence should be revealed one-by-one, in same position, on timer
- [x] After 5 sentences have shown, play wrap-up video(/video/wrapup_[Celeb].mp4), then go to '/take-back-control' page

**Comment by dhowe** [comment]
@billposters will provide video

**Comment by billposters** [comment]
Wrap up video plays over the top of this page when they click next

**Comment by dhowe** [comment]
Need video link

**Comment by billposters** [comment]
Latest screenshot: 

![IMG_6643](https://user-images.githubusercontent.com/48989022/58768240-03613d80-8590-11e9-9a5d-cd03d8633696.JPG)

**Comment by pauljervis** [comment]
@billposters don't have a spec for this ticket. Could I get one, please?

**Comment by billposters** [comment]
@pauljervis 
Design Spec:

![OCEANReveal_design_spec](https://user-images.githubusercontent.com/48989022/58873567-8b456580-86be-11e9-9fad-9a3f0e345986.jpg)

**Comment by billposters** [comment]
@pauljervis - just added the spec. Please message if anything is unclear.

On 04/06/2019 11:26, pauljervis wrote:
> @billposters don't have a spec for this ticket. Could I get one, please?
>
-- 
Barney Francis

Honorary Research Fellow  
School of Arts, Languages and Cultures
University of Manchester

http://www.billposters.ch

**Comment by dhowe** [comment]
@billposters Its absolutely essential that we show the users OCEAN scores here (a simple bar graph is all that's required.

**Comment by dhowe** [comment]
@pauljervis can you submit your PR for this (not sure how it didn't get in last nights build)
