### ISSUE TITLE
TakeBackControl page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#236]
- [x] implement design below
- [x] 'KEEP' button links to Goodbye page 
- [x] 'DELETE' button links to WeAreSorry page

**Comment by billposters** [comment]
Design Spec: 

![TakeBackControl_design_spec](https://user-images.githubusercontent.com/48989022/58755703-09e4ac00-84e1-11e9-9e8f-88bfb20e197f.jpg)

**Comment by billposters** [comment]
Latest screenshot: 

![IMG_5695](https://user-images.githubusercontent.com/48989022/58768244-2b50a100-8590-11e9-9f57-7efeeb899872.JPG)

**Comment by pauljervis** [comment]
@billposters this wasn't merged to master, did you pull that from the 236_TakeBackControl-page-spec branch?

**Comment by dhowe** [comment]
@billposters can you clarify what needs to be done here?
