### ISSUE TITLE
WeAreSorry page spec.

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#237]
- [x] align text correctly (same words on each line)
- [x] correct font weights
- [x] make text an interstitial, fades in and auto loads next page after 3 seconds
- [x] Autoloads 'goodbye' video from database (random selection TBC) to end the UX

**Comment by billposters** [comment]
Design Spec: 

![TakeBackControl_design_spec](https://user-images.githubusercontent.com/48989022/58755736-b0c94800-84e1-11e9-881d-b09d244abf15.jpg)

**Comment by billposters** [comment]
DESIGN SPEC: 

![WeAreSorry_Design_Spec](https://user-images.githubusercontent.com/48989022/58768258-6357e400-8590-11e9-9b22-c3960e3ece1c.jpg)

**Comment by dhowe** [comment]
On-hold pending new page dimensions for tablet screen
