### ISSUE TITLE
Buttons should not highlight when touched 

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#242]
![IMG_1330](https://user-images.githubusercontent.com/737638/58644864-13f88600-82fa-11e9-9e02-164c1b40aeb3.jpg)

**Comment by joseph-allen** [comment]
why not?

**Comment by aaronalbinson** [comment]
https://stackoverflow.com/questions/25704650/disable-blue-highlight-when-touch-press-object-with-cursorpointer

Doing this fix now

**Comment by aaronalbinson** [comment]
@billposters @dhowe if you can test this on the touch screen that would be ace

**Comment by dhowe** [comment]
thanks for this — will test tomorrow!

**Comment by billposters** [comment]
Will do, we can test tomorrow morning as the gallery is closed now!

Barney

On 30/05/2019 18:28, aaronalbinson wrote:
> @billposters @dhowe if you can test this on the touch screen that would be ace
>
-- 
Barney Francis

Honorary Research Fellow  
School of Arts, Languages and Cultures
University of Manchester

http://www.billposters.ch
