### ISSUE TITLE
Align progress bar numbers in header

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#262]
![image](https://user-images.githubusercontent.com/737638/58751683-a6835b80-8499-11e9-898f-11b7f675fdfd.png)

**Comment by pauljervis** [comment]
Worked on and pushed. Some deployment steps were failed within CD - https://github.com/dhowe/spectre/pull/263

**Comment by dhowe** [comment]
Not sure if this is related to your PR, but please give a check

![Screen Shot 2019-06-02 at 12 42 21 AM](https://user-images.githubusercontent.com/737638
/58754784-9dad7c80-84cf-11e9-80c4-8b56403860eb.png)

**Comment by billposters** [comment]
Looks good on screen now!
