### ISSUE TITLE
New header/footer images of correct dimensions

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#264]
Header/footer should probably be significantly less tall for new orientation, but wider (1920 wide).
We might also consider images on left/right of screen as well or instead

**Comment by billposters** [comment]
Ok I can resize the header / footer images, what are the dimensions? Any guidance would be great for the vertical

**Comment by dhowe** [comment]
screen is now 1920x1080... should use minimal space for any header/footer
ideally such content would move to 'siders'

**Comment by dhowe** [comment]
You can always look at the current site, on your own laptop, or on the 'server'.

Images are 150, headers and footers are 200 each

this wastes nearly 40% of our vertical space

**Comment by billposters** [comment]
Thanks for this. Really helpful. They are indeed a little large. Perhaps you can instruct Raymond to make them smaller as part of the design process?

I've added the draft of the design brief for feedback here: https://drive.google.com/drive/folders/1mKgjIYMakU5iEdgJRdnUlStZydkWIVfN

**Comment by dhowe** [comment]
again, perhaps this should be added to the design brief (reduce size of headers/footers)
