### ISSUE TITLE
Missing page if user chooses not to share ad on 'target-ad' page

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#268]
@billposters where should this link to?

**Comment by billposters** [comment]
@dhowe - a version of the 'successad' that says 'your targetted ad was unsuccessful'

**Comment by dhowe** [comment]
@billposters  if they dont share it, then its not really unsuccessful ...
I think we want to force them to 'share' it either way, no ?
Like, a 'Sorry, Spectre requires sharing...'
