### ISSUE TITLE
Subtitles (English) for all videos

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#282]
Bill, Iris can help out with creating the subtitle files, but it would be useful if she had the text files... can you attach below?

**Comment by billposters** [comment]
that is great if Iris can help. it may be easier / quicker to add the subtitles in Premier Pro and then export with embedded captions. is this the method you were thinking of?

**Comment by dhowe** [comment]
was thinking of using actual subtitle files, so that we don't need to re-render for each language, but for short-term your method is probably easier/quicker -- in any case, we still need the text-files to double-check against the videos...

**Comment by billposters** [comment]
To add the subtitles in Premier for 45 + videos is a lot of work and I can't do this task with current workloads. Who could we pay to do it? We can probably spare a few £100s to get someone on board to do the work.
