### ISSUE TITLE
Styling for error dialogs

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#284]
Maybe only one so far, on invalid email:

![image](https://user-images.githubusercontent.com/737638/58801632-fb8eb100-8602-11e9-9c85-3aaaa9d0e250.png)

**Comment by dhowe** [comment]
Pls style to match design

**Comment by kennyviperhk** [comment]
![Screenshot 2019-09-09 at 1 39 43 PM](https://user-images.githubusercontent.com/4047303/64505713-68eb6580-d307-11e9-854d-1c8975f11ad2.png)

**Comment by dhowe** [comment]
and this is for ALL dialog boxes, yes?

**Comment by kennyviperhk** [comment]
yes and Seem Login page is the only page using dialog boxes, and now are consistent.

Game is using a png so I can't change that.
![Screenshot 2019-09-11 at 4 14 06 PM](https://user-images.githubusercontent.com/4047303/64679896-3aa88a00-d4af-11e9-9912-1ad60b5142ff.png)

**Comment by dhowe** [comment]
We will also need styled dialogs for https://github.com/dhowe/spectre/issues/111
which should be the next ticket (please follow priority labels)

**Comment by dhowe** [comment]
Not sure why, but I'm still seeing the old dialogs

![image](https://user-images.githubusercontent.com/737638/71175080-99955080-22a1-11ea-8e14-e423e3fbc16e.png)

**Comment by dhowe** [comment]
see #348
