### ISSUE TITLE
Create OCEAN Top Bar component 

### ISSUE THREAD

**Issue by billposters** [dhowe/spectre#285]
- [ ] Build new OCEAN top bar component and add as header content for pages #216  , #217  . #218 and #219 ONLY

** new redesign is 300 x 1080 to match header dimensions
** Most elements of OCEAN profile used on page InsightComplete can be reused for this version.

**Comment by billposters** [comment]
Design Spec: 

![OCEAN_Profile_Bar_300_x_1080](https://user-images.githubusercontent.com/48989022/58810110-2bdf4b00-8615-11e9-8996-045818f1958c.jpg)

**Comment by dhowe** [comment]
on-hold
