### ISSUE TITLE
Hide Cursor (app-wide) when running on touch screen

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#298]
Cursor must start fully hidden, and ONLY appear with a specific key press, 'p' perhaps (on any page). 

This is high-priority -- try to implement in Navigation.jsx

**Comment by dhowe** [comment]
status on this @pauljervis

**Comment by dhowe** [comment]
we still really need this functionality @pauljervis @aaronalbinson 
thanks

**Comment by dhowe** [comment]
on-hold for touch-screen testing

**Comment by kennyviperhk** [comment]
fixed in #373

**Comment by dhowe** [comment]
what is the key?
