### ISSUE TITLE
Page: Game

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#31]

**Comment by joseph-allen** [comment]
![image](https://user-images.githubusercontent.com/7880824/56085628-5a734d80-5e3e-11e9-9609-5ac8583b050d.png)

**Comment by dhowe** [comment]
I can knock out a working version with the canvas if you want ?

**Comment by joseph-allen** [comment]
sure, barney said the Cambridge team was working on this for us?

**Comment by dhowe** [comment]
No, not the front-end.

**Comment by joseph-allen** [comment]
ah okay, we will need one we can extract the data out of then, but otherwise all good

**Comment by dhowe** [comment]
Test URL: http://rednoise.org/spectre/web-client/src/Canvas/brands

**Comment by joseph-allen** [comment]
wow awesome, did you make that? or they did?
