### ISSUE TITLE
Keyboard should start with shift-pressed

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#315]
See: https://github.com/hodgef/react-simple-keyboard/issues/79 and https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-autocaps-module/tree/master/ for simple solution

**Comment by kennyviperhk** [comment]
@dhowe since the Capital Letter should be for the name field, I have made it "SHIFT Pressed" on the first character.
Email field is ignored for this case

**Comment by dhowe** [comment]
see #348
