### ISSUE TITLE
Add TERMS OF SERVICE

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#318]
- [x] Write/Find TOS document ~[BF]~ [DH]
- [x] add link from LoginPage to TOS page, use placeholder text for now  [KW]

**Comment by kennyviperhk** [comment]
for TOS page, you want a pop-up or separate page?

**Comment by dhowe** [comment]
A small link on the page, then, if clicked, a popover I think

**Comment by billposters** [comment]
hi!

I think we talked about a pop up box

@Dan - can  we confirm?

Barney

On 06/09/2019 11:22, Kenny Wong Chi-Chuen wrote:
> for TOS page, you want a pop-up or separate page?
>
-- 
Barney Francis

Honorary Research Fellow  
School of Arts, Languages and Cultures
University of Manchester

http://www.billposters.ch

**Comment by dhowe** [comment]
yes, popover, as above

**Comment by billposters** [comment]
shall we put some stupid stuff in the TOS as we talked about?
ie. keys to your house, your grandma's car etc?

**Comment by dhowe** [comment]
definitely need to include user of data, images, etc. but we could further, though remember it is on the first page

we might also include a link to it if we end up with sidebar navigation... perhaps when clicked, it either says, 'sorry, you've already agreed', and/or simply asks for more information

**Comment by billposters** [comment]
nice touch! As long as we don't scare people off and bury the meat of the data uses etc using same dark design strategy you have suggested i'm fine with it being playful.

**Comment by dhowe** [comment]
in any case, we need some terms of service to start with... they should be long and detailed, similar to what facebook or google uses -- then we can add the bits about webcam images, follow-up etc

**Comment by billposters** [comment]
cool can you action Kenny to do this task?

**Comment by dhowe** [comment]
ill do it
