### ISSUE TITLE
Marina: video and audio out of sync

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#321]
perhaps the voice should be redone in any case -- I have a friend who is willing to try

**Comment by billposters** [comment]
Ok i'm up for getting it redone however it would need to be a lip sync only, we can't get canny to redo the VDR I don't think.

iF the audio and video are out of sync perhaps I can try and fix it in premier first?

**Comment by dhowe** [comment]
Yes, audio and lip sync only. We could try to fix the video/audio sync but the voice doesn't really work for me.  I have a friend who is happy to  try another take, but again, need the text file...

**Comment by billposters** [comment]
this may be a lot of additional work for very little gain. I would rather this was low priority / desirable not essential.

**Comment by dhowe** [comment]
Getting someone to lipsync it is not very much work... but agreed it is not an 'essential'

**Comment by billposters** [comment]
ok if we can put this on hold that would be great.

**Comment by dhowe** [comment]
its assigned to me

**Comment by dhowe** [comment]
@billposters for re-syncing
