### ISSUE TITLE
Ad image (leave/remain) alignment

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#322]
![image](https://user-images.githubusercontent.com/737638/59109000-1c714200-8934-11e9-8d52-c950ab86e0b1.png)

**Comment by dhowe** [comment]
Please check (may be fixed already)

**Comment by kennyviperhk** [comment]
looks like it is fixed

**Comment by kennyviperhk** [comment]
›
![Screenshot 2019-09-06 at 3 52 48 PM](https://user-images.githubusercontent.com/4047303/64410805-69dd8680-d0be-11e9-9696-21205ab5d685.png)

**Comment by dhowe** [comment]
its much better now, but should be bottom aligned with the larger image:

![image](https://user-images.githubusercontent.com/737638/64470133-a10c7000-d170-11e9-9605-6617c08c92d0.png)

**Comment by kennyviperhk** [comment]
<img width="294" alt="Screenshot 2019-09-09 at 4 02 15 PM" src="https://user-images.githubusercontent.com/4047303/64513473-38152b80-d31b-11e9-9dfa-7ff0b3479190.png">
<img width="290" alt="Screenshot 2019-09-09 at 4 02 04 PM" src="https://user-images.githubusercontent.com/4047303/64513483-3ba8b280-d31b-11e9-99bc-b6760e829d17.png">
fixed
