### ISSUE TITLE
Video: levels wrong on SpectreIntro.mp4

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#339]
- [ ] Adjust levels
- [ ] Text should read 'crises', not 'crisises'

**Comment by billposters** [comment]
yes will re-record and normalise audio

**Comment by dhowe** [comment]
Question: do we want to use the same voice (voice of the company) for both SpectreIntro and OceanIntro? @oscaryfish is happy to do Ocean Intro but we both quite like the current voice on SpectreIntro. Probably makes sense to do both in the same recording setup

**Comment by billposters** [comment]
Yeah same voice i think. 

Sally is the voice over artist on the Spectre intro vid! I can ask if she can do it for both but it will take us back to the question concerning buying a microphone here...

**Comment by dhowe** [comment]
Yes, I know it is Sally. Fine if you guys want to do it there.

**Comment by billposters** [comment]
budget cost isn't really fine though,if you have equipment already, may be best to do it there!
