### ISSUE TITLE
Video: redo voice for OceanIntro.mp4 

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#340]

**Comment by billposters** [comment]
I'll get on this next week. It would be really useful to get a full UX gant put together if possible so I can get you what you need when you need it. 
Be good to discuss this on our call tomorrow.

**Comment by billposters** [comment]
I think a female voice is better, I can record new audio here in Kampala I think. will need to put a microphone cost into the budget though.

**Comment by dhowe** [comment]
Can we not borrow a microphone somewhere? We can here, and D can possibly do it? Save $100 or so..

**Comment by billposters** [comment]
amazing, that would be ace!

**Comment by dhowe** [comment]
please paste the text here

**Comment by dhowe** [comment]
> Question: do we want to use the same voice (voice of the company) for both SpectreIntro and OceanIntro? @oscaryfish is happy to do Ocean Intro but we both quite like the current voice on SpectreIntro. Probably makes sense to do both in the same recording setup

**Comment by billposters** [comment]
> Can we not borrow a microphone somewhere? We can here, and D can possibly do it (I'll have to ask her)? Save $100+ on mic/interface..

is this still the plan for the voice overs?

**Comment by dhowe** [comment]
No, the revised plan was for you guys to tweak the existing spectre video and record the OCEAN video so that it is a uniform voice throughout (if this requires buying a mic, then so be it) .

**Comment by billposters** [comment]
Ok if we use this route, it may take a while to find a good mic here in Kampala. I'll start looking this weekend and update as and when.

**Comment by dhowe** [comment]
probably a usb mic is the best bet, otherwise you will also need an audio interface

**Comment by billposters** [comment]
good shout, I'll check it out

**Comment by dhowe** [comment]
progress on this?

**Comment by billposters** [comment]
no usb mics were available to buy in Kampala. Can this be done on your side @dhowe with D?

**Comment by dhowe** [comment]
could have been done quite easily last week, now it requires a trip to locked-down university, health declarations, etc
