### ISSUE TITLE
Animation sizing

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#341]
Note that animations (currently 1320x1080) will either need to be resized or will cover header/footer

**Comment by billposters** [comment]
I think resize to width of screen with header and footer visible, what do you think?

**Comment by dhowe** [comment]
yes, that works for me (once we've detemined footer/header size if we need them at all)

**Comment by billposters** [comment]
perfect. Can you pass on the header / footer dimensions that Raymond uses and i can pass them to Stephen for the animations.

**Comment by dhowe** [comment]
did you see my tg msg re: design?

**Comment by billposters** [comment]
Waiting on Pete's design system before we can sign this one off. Should be able to sign off Monday 3rd feb.
