### ISSUE TITLE
Campaign for US context

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#345]
to replace: 

![image](https://user-images.githubusercontent.com/737638/71308452-d09d6a80-2437-11ea-91db-eedfc2c56ff3.png)

**Comment by billposters** [comment]
We should also replace images in the dark ad archive too, and look over all slogans so images and text combinations work in the US 2020 election context

**Comment by dhowe** [comment]
indeed, but first is picking the 'issue', a yes/no, stay/leave type decision...

**Comment by billposters** [comment]
Apologies I missed this latest comment here. What could our options be? Important criteria for me: 

- time / cost 
- as simple and effective as possible 
- related to the current IRL context of US 2020 election cycle

**Comment by dhowe** [comment]
using the election itself is one possibility, though we'd have to decide how this is framed: trump vs demo-candidate, or democrat vs republican, or...

another approach would be to use a more specific election issue: abortion, environment, immigration, etc

another option involves 3rd party candidates,  which are always a big issue in US elections: "Cindy loves the green-party candidate and knows they would make the best president, but also knows they have little chance of actually winning. Your job is to convince her to vote for the democrat in order to defeat Trump...

**Comment by billposters** [comment]
dem / rep is my choice for ease and effectiveness. We don't know who
will be the dem candidates etc.

Issue based narratives will be interesting if there are multiple choices
but the psychometric models will take a while to put together. Would be
strong though.

We would probably need outside consultancy from a psychometrician to
ensure it's on point

**Comment by dhowe** [comment]
as discussed elsewhere, I think we should ask cambrdige to provide this outside consultancy as part of their original terms

**Comment by billposters** [comment]
ok. Aside from Vess et al's input. what context are we going with? Rep / Dem? Once decided i can source imagery and complete slogans

**Comment by dhowe** [comment]
thats fine... the only issue is that there are strong republicans who wouldn't consider voting for trump, but I suppose we can work that out in the text...

**Comment by dhowe** [comment]
Waiting on assets (icons, dark-ad slogans and images, etc)

**Comment by billposters** [comment]
working on these this week. Will be with you EOP friday, is that ok?

**Comment by dhowe** [comment]
ok

**Comment by billposters** [comment]
Still on track for sending the first batch of new assets over to you by EOP tomorrow.

**Comment by billposters** [comment]
First draft of dark ad images and proposed slogans are in the drive for review: https://drive.google.com/drive/folders/1lB3N_A39qiyQheZNhdGbKrUg_2dvlL8J

**Comment by dhowe** [comment]
pls see tg messages

**Comment by billposters** [comment]
did you review these slogans / images @dhowe ?

**Comment by dhowe** [comment]
Influenced-by-themes, influenced-by-images, and two slogans selected and integrated

any further edits should happen (here)[https://github.com/dhowe/spectre/blob/master/shared/user.js#L523] and (here) [https://github.com/dhowe/spectre/blob/master/shared/user.js#L592]

@billposters pls compile a starter set of images in a single folder, labelled by category, as we have for the UK:
```

democrat_5.1.png
democrat_5.2.png
democrat_4.1.png
democrat_4.1.png
democrat_3.2.png
democrat_3.1.png
democrat_2.2.png
democrat_2.1.png
democrat_1.2.png
democrat_1.1.png

democrat_-1.1.png
democrat_-1.2.png
democrat_-2.1.png
democrat_-2.2.png
democrat_-3.1.png
democrat_-3.2.png
democrat_-4.1.png
democrat_-4.2.png
democrat_-5.1.png
democrat_-5.2.png

(and same for 'republican')
```

**Comment by billposters** [comment]
Sure. can you confirm that x.1 should = low trait score / x.2 = high trait score ?

I will apply the same method to both rep / dem.

**Comment by dhowe** [comment]
No. As before these correspond to the category system we devised for sheffield, with 2 images for each of 10 categories (-5 to 5).

{adIssue}_{category}.{image#}.png

We categorize each according to OCEAN-group from -5 to 5, according to OCEAN acronym (O=1, C=2, etc):
   * positive numbers mean 'high', negative numbers mean 'low',
   * 0 means the user is neutral and gets random assignments
