### ISSUE TITLE
Video no longer found on LoginPage

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#354]
ERROR: "Unable to load video component"

**Comment by kennyviperhk** [comment]
<img width="536" alt="Screenshot 2019-12-27 at 1 57 04 PM" src="https://user-images.githubusercontent.com/4047303/71503961-5d21b000-28b2-11ea-964f-f504d2029bd0.png">
seem works fine with me?

**Comment by dhowe** [comment]
yes, apparently a problem on chromium
lets standardize on chrome
