### ISSUE TITLE
Contact iiyama tech support for blurry lens

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#381]

**Comment by kennyviperhk** [comment]
I have tested and checked the spec of the camera.
it is 0.9 megapixel means 720p.
photobooth only can access low resolution(640 × 426) for some reason. able to access higher resolution with web js now
it is not as sharp as MacBook camera but not blurry now
iiyama camera
![iiyama cam](https://user-images.githubusercontent.com/4047303/72242850-540c3f00-3625-11ea-920c-36c5a3f8d72e.jpg)
macbook camera
![macbook cam](https://user-images.githubusercontent.com/4047303/72242852-540c3f00-3625-11ea-9d53-ea37a810e452.jpg)
