### ISSUE TITLE
Show user-avatar with webcam image on top-bar for testing

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#399]
For testing we need to display the avatar component in the header, using the current user's image from the webcam, starting on 'data-is' and going until 'game' (3 pages total)

Alternatively, we can simply add the avatar-component to the dialog before the game starts (whichever is easier -- the point is just to be able to see the image we have taken when testing height/tilt)

I've started it in the header here -> client/src/Components/SpectreHeader/SpectreHeader.jsx, maybe just css adjustments needed now

**Comment by kennyviperhk** [comment]
fixed in #373 PR
