### ISSUE TITLE
Game: full width/height and full set of brands

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#400]
- [x] Full width and height of screen
- [x] Full set of brands/icons (see notes below)

**Comment by kennyviperhk** [comment]
updated in #373 PR

**Comment by kennyviperhk** [comment]
what do you mean by full set of brands?
it has 20 in the list/game now

**Comment by dhowe** [comment]
there were originally a few more -- i'll have to do some research
all good

**Comment by dhowe** [comment]
@billposters  - please check whether we actually want more brands. I don't think we want to increase the time for the game, so the only way to do this is to reduce the space between the brands

**Comment by billposters** [comment]
@dhowe - Quick question, do more brands = more accurate OCEAN profile?

**Comment by dhowe** [comment]
good question -- i'm not sure

**Comment by billposters** [comment]
I think it would if it was working as designed right?

**Comment by dhowe** [comment]
not sure what you mean... but clearly there is a window below which results are meaningless (1 brand, for example), and over which the added brands aren't likely to help... maybe a question for vess

**Comment by billposters** [comment]
Yeah I agree, it would be tricky to ask Vess in relation to how things currently stand...

**Comment by billposters** [comment]
i would of thought that more pre-weighted data sets for brands would = more accuracy

**Comment by dhowe** [comment]
we are currently using 20 of the 34 brands that cambridge sent 
the ones we are NOT using are:

cocacola, playstation, pepsi, burberry, topshop, gap, calvin klein, next, swarovski, tommy hilfiger, marks and spencer, vivienne westwood, nintendo64, lego

**Comment by billposters** [comment]
ok cool, does more brands = more accurate OCEAN profile? 

If not, why not? Surely adding in more pre-weighted data sets from facebook for each brand will improve likely OCEAN traits?

**Comment by dhowe** [comment]
> @billposters - please check whether we actually want more brands. I don't think we want to increase the time for the game, so the only way to do this is to reduce the space between the brands

**Comment by billposters** [comment]
> > @billposters - please check whether we actually want more brands. I don't think we want to increase the time for the game, so the only way to do this is to reduce the space between the brands

understood, but this doesn't help me understand what is happening in the BE and how more brands could be more beneficial. Can you explain how the accuracy works so i can see if more brands would be better?

**Comment by dhowe** [comment]
please check speed of moving icons now that full brand list has been added

**Comment by dhowe** [comment]
I've now removed a few duplicate and uk-centric brands and increased their size - please verify

**Comment by dhowe** [comment]
@billposters please feedback on the following after touchscreen test:
1. number of brands/speed 
2. size of brand circles
3. appearance of brands (are they flickering?)
3. frames-per-second (press the f-key on the keyboard while game is running)
