### ISSUE TITLE
Add GDPR (dark) design dialog before TOS

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#402]
On Login page: 
If user clicks ‘Terms of Service’, they get Yes/No dialog with link at bottom.
If Yes, continue. 
If No, back to 'touch-to-begin'.
If click link, then show full TOS page (as overlay or separate page)

![image](https://user-images.githubusercontent.com/737638/72658766-b0d67380-39f0-11ea-9081-174065480e11.png)

Use Spectre+logo instead of Quantcast. At bottom the link should be 'Read our Privacy Policy', instead of 'Show Purposes'.

https://www.leonpaternoster.com/posts/techradar-gdpr/
https://www.quantcast.com/gdpr/consent-management-solution/

**Comment by dhowe** [comment]
At Spectre, we take privacy very seriously. Our Privacy Policy will help you understand what information we collect and process, how we use it, and what choices you have about your personal data. By accessing this site, you consent to the terms of this Policy and agree to be bound by it and our Terms of Use.

[link]

**Comment by dhowe** [comment]
could also look like this:

![image](https://user-images.githubusercontent.com/737638/72885739-74ce4600-3d43-11ea-847c-e1c43c16f1a5.png)

**Comment by dhowe** [comment]
@kennyviperhk @peterbix  we are trying to mimic the dark design patterns found on current GDPR sites. The first pop-up should be a normal, small dialog box in which the ACCEPT button is more prominent. If the user skips the 'accept' and 'not accept' buttons, and instead clicks the TOS button, then they should get a full-age overlay with the many pages of TOS legalese.

**Comment by dhowe** [comment]
Still need design for both dialog and full-height overlay with long text

**Comment by billposters** [comment]
is this added to @peterbix 's list?

**Comment by dhowe** [comment]
been there for many days:

![image](https://user-images.githubusercontent.com/737638/75059544-28c81a00-5518-11ea-85ee-8c0fbf412257.png)

**Comment by dhowe** [comment]
Again, this needs the 'I accept' button to be pre-selected, blue, and larger than the other
