### ISSUE TITLE
Wireless keyboard / trackpad for install

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#410]
Microsoft Wireless All-In-One Media Keyboard (N9Z-00001)

**Comment by billposters** [comment]
thanks for this dan, will get them ordered.

**Comment by billposters** [comment]
Ordered 7 x keyboards to spec above. Will be delivered to testing venue on Monday 3rd Feb. Budget updated in drive.

**Comment by billposters** [comment]
this can be closed now. we have all keyboards on site
