### ISSUE TITLE
Convert/clean TOS for login page overlay

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#412]
[google_privacy_policy_en.pdf](https://github.com/dhowe/spectre/files/4096523/google_privacy_policy_en.pdf)

see also #402 (user should first see that page, then if click again to see TOS, see the page as above

discuss with me if it is at all difficult to convert the above to html (not worth much time as we can get another version)

**Comment by kennyviperhk** [comment]
[google_privacy_policy_en _converted.html.zip](https://github.com/dhowe/spectre/files/4102107/google_privacy_policy_en._converted.html.zip)
still need some manual fine tune with the code i guess

**Comment by dhowe** [comment]
lets at least add some placeholder for the 2 overlays to the site:
- [ ] short dialog box (yes/no/link)
- [ ] terms of service overlay

**Comment by dhowe** [comment]
the initial dialog box is still missing

**Comment by dhowe** [comment]
text also far too big in TOS overlay

![image](https://user-images.githubusercontent.com/737638/73915895-3f0a8f00-48f7-11ea-80ec-3d6ff05e6880.png)

**Comment by dhowe** [comment]
Overlay should be full width of page, text should be small/dense.

**Comment by kennyviperhk** [comment]
it's ready for edit. just change the HTML inside LoginPage/TOS.jsx
