### ISSUE TITLE
Video: need text for multiple videos

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#417]
- [x] Intro To Spectre 

- [x] OceanIntro.mp4 

- [x] Marina Statements

**Comment by billposters** [comment]
Scripts & voice over briefs for 2 x UX videos (intro to Spectre, intro to ocean) here:

https://drive.google.com/drive/folders/11Z-OcC20nLk9le5nXYevDoPLUsJp8wcm

- Prototype videos are included in the sub folder for reference when recording new audio assets

- please read voiceover brief carefully and ensure timecodes are matched in new recordings.
