### ISSUE TITLE
Icons alignment problem in OCEAN Profile component

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#419]
![image](https://user-images.githubusercontent.com/737638/73133576-ae65c080-4065-11ea-9ccb-7a025ec5833f.png)

**Comment by cqx931** [comment]
please check: https://github.com/dhowe/spectre/pull/427

**Comment by dhowe** [comment]
Still doesn't look quite right to me: 3 elements (slider, image, percent-number) all need to be center-aligned

**Comment by cqx931** [comment]
can this be closed now? @dhowe
