### ISSUE TITLE
Game "undefined" mouseX / mouseY issue

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#436]
<img width="367" alt="Screenshot 2020-01-29 at 11 51 09 AM" src="https://user-images.githubusercontent.com/4047303/73329349-59f65700-4298-11ea-9a65-5967a8854fbf.png">
probaly related to mouse / touch issue
doesnt affect gamplay.

**Comment by dhowe** [comment]
ok, lets keep an eye on this
