### ISSUE TITLE
Incorrect CSS (on production server only)

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#437]
button should be blue and with boarder
![image](https://user-images.githubusercontent.com/737638/73591857-dbffad80-452e-11ea-9342-cd13e44f9edf.png)

<img width="646" alt="Screenshot 2020-01-29 at 1 10 39 PM" src="https://user-images.githubusercontent.com/4047303/73329560-0cc6b500-4299-11ea-89c0-05ff180fd376.png">

**Comment by kennyviperhk** [comment]
fixed by not using var in CSS for now
https://www.w3schools.com/css/css3_variables.asp

the CSS (for this button) is rendered by react in this case so it might be caused by different react versions.

**Comment by dhowe** [comment]
See #441
