### ISSUE TITLE
OCEANReveal: make generated text appear one letter at a time

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#445]
this should be like a typewriter effect...

**Comment by cqx931** [comment]
please check https://github.com/dhowe/spectre/pull/473

**Comment by dhowe** [comment]
great @cqx931 
I made some adjustments as well
see #479 for a small tweak

**Comment by dhowe** [comment]
if its easy, lets add a subtle typing sound, like in automatype

**Comment by cqx931** [comment]
How about adding some extra space to make it less strange?
![image](https://user-images.githubusercontent.com/3056154/75264547-9052c380-57bd-11ea-85d2-17ac6074ceb7.png)

**Comment by dhowe** [comment]
Sure, that helps. But I think the problem is really when we have two long lines and two very short lines. If you hit the 'c' key while on the page, you should get a different set of text each time...

**Comment by cqx931** [comment]
Another option would be displaying all generated sentences in one paragraph and taking considerations of orphans only on the last line.
![image](https://user-images.githubusercontent.com/3056154/75283776-77f4a000-57e1-11ea-8097-6061ef12b1c4.png)

**Comment by dhowe** [comment]
I think this is a good suggestion -- lets do it...

**Comment by dhowe** [comment]
looks good
