### ISSUE TITLE
confirm layout for Login Page

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#447]
Need a confirmed visual layout for the virtual keyboard placement / interaction

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/74428041-384dc000-4e93-11ea-9923-746ffeda0d6a.png)

**Comment by peterbix** [comment]
I really think keyboard needs to be an overlay as it is on all touch screen OS

**Comment by dhowe** [comment]
ok, but need design..
