### ISSUE TITLE
Webcam not working on mac mini

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#450]
Critical as we cannot test position in the monolith (in Manchester) without webcam images

![20200205_135107](https://user-images.githubusercontent.com/737638/73852713-a3334180-486a-11ea-8de8-0509824b604a.jpg)

**Comment by kennyviperhk** [comment]
![Screenshot 2020-02-06 at 11 57 52 AM](https://user-images.githubusercontent.com/4047303/73904863-669e2f00-48d8-11ea-9ecb-1ffacae847f5.png)
i dont have webcam error but only cant access the image
