### ISSUE TITLE
Uncaught DOMException: CssStyle Sheets

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#451]
![Screen Shot 2020-02-05 at 10 53 10 PM](https://user-images.githubusercontent.com/737638/73853439-cf9b8d80-486b-11ea-914d-2e629f5df6db.png)

**Comment by kennyviperhk** [comment]
i can't reproduce this warning

Chrome / Chromium version bug/issue?
https://stackoverflow.com/questions/49161159/uncaught-domexception-failed-to-read-the-rules-property-from-cssstylesheet

**Comment by dhowe** [comment]
Closing for now, need to keep eye out for this on prod server
