### ISSUE TITLE
"Lag" in game interface with touchscreen

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#464]
there is bandwith being used here, so this is either a framerate problem (which can be tested by hitting the 'f' key), or a driver problem, which we will have to address with touch-base.

**Comment by billposters** [comment]
not experiencing a lag now after chgning the sensitivity settings etc on the touch driver. Will review with all 6 x machines prior to closing

**Comment by billposters** [comment]
this can be closed now. HUZZAH
