### ISSUE TITLE
Take-Selfie: 'Next' button should be disabled before image is taken

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#466]

**Comment by cqx931** [comment]
Isn't the button already disabled?
![image](https://user-images.githubusercontent.com/3056154/74260744-12c08b00-4cc8-11ea-8be5-66c549e6b931.png)
![Screen Shot 2020-02-11 at 12 15 00 PM](https://user-images.githubusercontent.com/3056154/74260802-2835b500-4cc8-11ea-903e-cb517970773a.png)

**Comment by dhowe** [comment]
Yes, sorry, I fixed it today... should have closed this ticket :/ my bad
