### ISSUE TITLE
Update design for Brand Game

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#467]
as per figma: https://www.figma.com/file/7s5ylebj7GTnfEA92NouPB/Spectre---Landscape

**Comment by dhowe** [comment]
perhaps just the smiley icons on the front-page, but any other design tweaks would be great too

**Comment by cqx931** [comment]
Design tweaks:
https://github.com/dhowe/spectre/pull/512/commits/e528caf7044944fbac6d67bff3f23e71bf2395ac
![image](https://user-images.githubusercontent.com/3056154/75199001-fdb81300-572f-11ea-8ded-89c2e504eb14.png)

Still need to change

- p5 text font
- instruction image

**Comment by cqx931** [comment]
Updated the instruction image, no need to load the font as I used all images instead of text in the p5 game.
https://github.com/dhowe/spectre/pull/519/commits/1f577e3fe618816693a2ea7bee7c1500bd718fe2
