### ISSUE TITLE
Use local fonts in App.jsx

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#468]
replace these with local fonts:
```

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
```

**Comment by cqx931** [comment]
Do you mean keep using the same fonts but host them by at https://github.com/dhowe/spectre/tree/master/client/src/Fonts/?

**Comment by dhowe** [comment]
yes, keep them in git... is there a reason not to?

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/spectre/compare/master...cqx931:master
Replaced with local fonts, though I don't see these two fonts in use at the moment.
