### ISSUE TITLE
Typography guidelines for text

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#471]
We should (in general) try to follow usability guidelines for text in the interface

**Guidelines**
- Max ~12 words per line (less if words are longer)
- Max of ~50-60 characters (spaces included) 
- No widows
- No orphans

![image](https://user-images.githubusercontent.com/737638/74218814-f59ab500-4ce5-11ea-980f-7a9848b6751b.png)

**Comment by peterbix** [comment]
While I respect your intention, guidelines are exactly that - just a guide. In my experience they should be followed but not used as strict laws that must be adhered to in every instance. What you have highlighted is a good example - the top line is 12 words long and contains 1 'long' word. The line underneath contains 18 words and 9/10 'short' words. To make the column shorter will result in children, so in this instance I feel keeping the lines complete is the best compromise.

**Comment by dhowe** [comment]
Totally agree with your general point re: guidelines. For me these lines are uncomfortable to read (plus we have so much space to play with), but its a tiny point in the grand scheme of things...  The point of the ticket is more to keep these _guidelines_ in mind throughout (especially re:  widows/orphans)

If we have time later, might be interesting to see what it would look like if the text was perhaps restricted to the width of the headline, so we get 4 lines instead of 2. But as I say, low priority...

**Comment by peterbix** [comment]
Updated, see what you think

**Comment by dhowe** [comment]
I think I prefer either that or below -- your thoughts?

![image](https://user-images.githubusercontent.com/737638/74317931-3c0c1480-4db7-11ea-8b56-44e97cb1ce5b.png)
