### ISSUE TITLE
Add SVG data for Consumer Data page in IconButton.jsx

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#475]
In /spectre/client/src/Components/IconButton/IconButton.jsx

Just placeholders now (.ai assets [here](https://drive.google.com/drive/folders/1iacu6KpiTFOfvEcbGNQtsE6GHeSg-hO0)):

![image](https://user-images.githubusercontent.com/737638/74423992-20bf0900-4e8c-11ea-9d4e-de09f9bd8398.png)

**Comment by billposters** [comment]
this is one for @peterbix not me
