### ISSUE TITLE
Bug on text-entry in keyboard (login page)

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#476]
To recreate:
1. add a name and an incorrect email, e.g., me@.com
1. close dialog box
2. tap or click to edit the email (after the @ sign, for example)
3. notice that the cursor appears in correct position but new characters are added at end

**Comment by billposters** [comment]
Also.. when clicking on the 'name' text field, the current text doesn't disappear until you start typing which will confuse users. We want the prefilled text on the name field to disappear when clicked / touched, like the email field does correctly.

**Comment by kennyviperhk** [comment]
fixed

also fixed spacebar - will add space for name but email will be ignored
