### ISSUE TITLE
Restrict text-width on OCEANReveal

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#479]
![image](https://user-images.githubusercontent.com/737638/74465125-c9db2300-4ecf-11ea-9179-478ed8e81bc6.png)

**Comment by cqx931** [comment]
Like this?
![image](https://user-images.githubusercontent.com/3056154/74954401-0f688600-53d1-11ea-9d40-e2911173d872.png)

**Comment by dhowe** [comment]
Perfect, though that text is dynamic of course...

**Comment by dhowe** [comment]
But we need to guard against widows or orphans (single word on any line):

![image](https://user-images.githubusercontent.com/737638/75001533-a5b5ae00-549c-11ea-9e83-dad98c717651.png)

**Comment by dhowe** [comment]
I did a quick hack to avoid widows
