### ISSUE TITLE
Update icons, slogans, ad-images for US context

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#480]

**Comment by billposters** [comment]
have you had a chance to review the image DB and suggested slogans @dhowe ?

**Comment by billposters** [comment]
there is also an issue with the horizontal red bar that is the background for the slogans when they appear overlayed on the images. the current position of the red bar obscures some important parts of images that we aim to use. 

there is also an arguement to include a 'VOTE 2020' icon above the republican / democrat logos, What do you think?

**Comment by dhowe** [comment]
> there is also an argument to include a 'VOTE 2020' or #US2020 text, What do you think?

I'm not sure about this

**Comment by dhowe** [comment]
@billposters where do you want the red bar moved to (or should it be only as wide as the text)?

**Comment by billposters** [comment]
> @billposters where do you want the red bar moved to (or should it be only as wide as the text)?

i'm not sure Dan, what do you think? Should we have red for republican and blue for democrat to mirror party colours? 

Locating the red bar with text centrally obscures some content on images. I can either edit the composition of these images to work with a coloured bar with text intersecting or as you suggsted we move the bar and/or shorten it.

**Comment by dhowe** [comment]
I would suggest getting the images selected first, then seeing how bad the problem is. After thinking about it, I don't thing shortening the bar horizontally would do much. 

One option is to simply specify the vertical position of the bar on a per-image basis (store one number per image, which is the vertical offset). 

Another option is to simply let the user drag the bar to where they want it.

**Comment by billposters** [comment]
ok sounds good to me. i'll label the images correctly and send you a link to the file when it's on the drive! then we can review as you've suggested.

**Comment by dhowe** [comment]
cool. please see the explanation of the required naming scheme in the ticket. also, just zip and place here if you can (better than drive)

**Comment by billposters** [comment]
can you confirm that low trait score = x.1, high trait score = x.2 on the naming scheme?

**Comment by billposters** [comment]
DEMOCRAT images; 
https://we.tl/t-FZuxTBKIvD
** exported as jpeg, to exact pixel dimensions of dark ad interface

**Comment by billposters** [comment]
DEMOCRAT Slogans (final version) attached...

[Democrat_Slogans & contributors.pdf](https://github.com/dhowe/spectre/files/4250389/Democrat_Slogans.contributors.pdf)

**Comment by billposters** [comment]
REPUBLICAN Images & Slogans 
** exported as web ready jpeg, to exact pixel dimensions of dark ad design tool page (642px_by_464px)

https://we.tl/t-vJe6aM9G1H
