### ISSUE TITLE
Ocean Profile Text needs update

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#486]
![Screenshot 2020-02-19 at 11 44 57 AM](https://user-images.githubusercontent.com/4047303/74800071-51c88f00-530d-11ea-8908-d6ea32433cad.png)

text should be dynamic?

**Comment by dhowe** [comment]
yes

**Comment by billposters** [comment]
The OCEAN profile sidebar should also include the following dynamic text at the end on two seperate lines: 

'[username] is influenced by images that contain [x]...'

'[username] is influenced by slogans that contain [x]...'

this is so they can refer back to this text during the dark ad design tool should they need to check / refresh their memory.

**Comment by dhowe** [comment]
that is a lot of text to present all at once

**Comment by billposters** [comment]
understood, but it is 2 x more short lines, that appear on the screen before the dark ad tool but folks will forget for sure!!

**Comment by dhowe** [comment]
The page just before the dark-ad has just those 2 lines (are you suggesting removing this page ?)

![Screen Shot 2020-02-21 at 8 09 32 PM](https://user-images.githubusercontent.com/737638/75033542-1e8d2800-54e6-11ea-8272-4ccaf536be41.png)

**Comment by billposters** [comment]
no not at all. i'm simply saying that during the UI / UX dev phases, we have always considered that users may forget the image / slogan prompt info and it was included on earlier versions of the side bar

**Comment by billposters** [comment]
[OCEAN_Top_bar_450px_by_1080px.pdf](https://github.com/dhowe/spectre/files/4235953/OCEAN_Top_bar_450px_by_1080px.pdf)

**Comment by dhowe** [comment]
Will need to adjust spacing, fonts, etc. in OceanProfile to accommodate extra text:

![Screen Shot 2020-02-23 at 7 24 40 PM](https://user-images.githubusercontent.com/737638/75111212-41e4de00-5672-11ea-82c9-cabbb53f0869.png)
