### ISSUE TITLE
Error: Cannot find module '.../node_modules/@tensorflow/tfjs-node/lib/napi-v4/tfjs_binding.node'

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#488]
Not sure what causes this problem from time to time (many reports elsewhere) but the following (from the top-level of the project) _usually_ fixes it:

$ npm rebuild @tensorflow/tfjs-node --build-from-source

**Comment by cqx931** [comment]
Just tried, but `$ npm rebuild @tensorflow/tfjs-node --build-from-source ` does not fix the issue for me.

**Comment by dhowe** [comment]
Another strategy: try copying the lib to its need location:

`$ cp lib/tfjs_binding.node node_modules/\@tensorflow/tfjs-node/lib/napi-v4/`
