### ISSUE TITLE
Insight: sliders don’t activate the next button on touch screen

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#505]
This works correctly in touch-screen simulation (see below). @billposters Are you saying that when you drag the slider, the 'next' button does not become active (and turn blue)?

![image](https://user-images.githubusercontent.com/737638/75002174-8455c180-549e-11ea-8d78-530b1962fa11.png)

**Comment by billposters** [comment]
yes exactly. slider isn't greyed out to start and when touched it doesn't activate next button. This is the same for all verification questions

**Comment by dhowe** [comment]
the next button is a bug for sure -- it works correctly on an emulated touchscreen, but apparently not on an actual touchscreen

but for me an active slider shouldn't be grayed out, only the next button should be grayed out -- when you move the slider the button should become active

**Comment by billposters** [comment]
let me know when you push an update, I can test here at the apartment today.

**Comment by dhowe** [comment]
near impossible to fix without being able to recreate... we'd just be trying random things -- to be clear, are you saying that one can't get past those screens using the touchscreen?

**Comment by billposters** [comment]
lets just get the button activated on touch as you have suggested.

**Comment by dhowe** [comment]
@kennyviperhk documented the correct touch driver settings so that the sliders will work as expected:

<img width="808" alt="Screenshot 2020-01-16 at 4 03 20 PM" src="https://user-images.githubusercontent.com/737638/75149248-8177fc80-573c-11ea-9cf0-0dfe56553cc7.png">
<img width="833" alt="Screenshot 2020-01-16 at 4 03 18 PM" src="https://user-images.githubusercontent.com/737638/75149252-8341c000-573c-11ea-81a1-807f18e086aa.png">
<img width="823" alt="Screenshot 2020-01-16 at 4 03 12 PM" src="https://user-images.githubusercontent.com/737638/75149253-8341c000-573c-11ea-8271-a3bfaa68f2bc.png">

**Comment by dhowe** [comment]
@kennyviperhk  apparently these settings had no effect

**Comment by kennyviperhk** [comment]
the touch software is simulating mouse clicks not screen touch

now I added mouse-up detection and it should be fine.

**Comment by dhowe** [comment]
ok, we'll test it tonight

**Comment by dhowe** [comment]
confirmed by tom
