### ISSUE TITLE
dark-ad logo

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#509]
need confirmation if the current dark-ad with new logo is alright, it is not yet updated in Figma.

![Screenshot 2020-02-24 at 10 43 23 AM](https://user-images.githubusercontent.com/4047303/75125918-80ba7880-56f2-11ea-8f1c-cfef36db4cab.png)

![Screenshot 2020-02-24 at 10 42 06 AM](https://user-images.githubusercontent.com/4047303/75125886-5799e800-56f2-11ea-978b-28dd5df721e1.png)

**Comment by dhowe** [comment]
Do you mean the elephant and donkey? I believe so (@billposters, can you confirm?)
(However the background images are not yet updated)

**Comment by billposters** [comment]
> Do you mean the elephant and donkey? I believe so (@billposters, can you confirm?)
> (However the background images are not yet updated)

- perhaps a slight adjustment to the alignment on the right hand side, the logos are very close to the edge of the image on that side.

**Comment by kennyviperhk** [comment]
fixed in #478
