### ISSUE TITLE
Game Logo Snapping

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#521]
![Screenshot 2020-02-26 at 1 55 58 PM](https://user-images.githubusercontent.com/4047303/75322705-4b5a8a00-58ae-11ea-8755-d6d870c26568.png)

for 'love' can snap above the second line,
but 'hate' can't

**Comment by dhowe** [comment]
good notice

**Comment by dhowe** [comment]
fixed, pls verify

**Comment by kennyviperhk** [comment]
![Screenshot 2020-02-28 at 11 53 17 AM](https://user-images.githubusercontent.com/4047303/75508980-f0956f80-5a20-11ea-94e5-32581d32ce27.png)
work fine now, but the topmost logos seem out of game canvas (cropped)

**Comment by dhowe** [comment]
The header image should have a transparent background here.
I've added a 'transparent' property to SpectreHeader which hides the divider -- you should also use it to show the image with transparent background

**Comment by kennyviperhk** [comment]
![Screenshot 2020-02-28 at 1 17 38 PM](https://user-images.githubusercontent.com/4047303/75512604-f3965d00-5a2c-11ea-8680-1d5988a6895e.png)

it is not related to the header, it is out of game canvas

**Comment by dhowe** [comment]
creating new issue
