### ISSUE TITLE
Pick-your-side and launch campaign text

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#522]
![Screenshot 2020-02-26 at 3 55 38 PM](https://user-images.githubusercontent.com/4047303/75323758-7645dd80-58b0-11ea-97ea-4e4c95345a5b.png)
![Screenshot 2020-02-26 at 3 56 03 PM](https://user-images.githubusercontent.com/4047303/75323776-83fb6300-58b0-11ea-8c5c-5b1ee3d5b250.png)
launch-campaign is uppercase

**Comment by kennyviperhk** [comment]
uppercase or normal?

**Comment by dhowe** [comment]
whatever is easier

**Comment by kennyviperhk** [comment]
fixed in #478
