### ISSUE TITLE
Add new .svg brand images

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#531]
(sent to you via email) check we have all the files we need and that everything works correctly in the game. Should only involve changing file extension in code from png to svg and replacing the files in /client/public/imgs

**Comment by kennyviperhk** [comment]
removed Zara and Rayban from the code to work as they don't have the .svg
squared logos are too big and out of the circle

![Screenshot 2020-02-27 at 3 25 06 PM](https://user-images.githubusercontent.com/4047303/75421541-7a87fe80-5975-11ea-9d75-5510c935a747.png)

**Comment by dhowe** [comment]
@billposters rayban and zara missing

**Comment by dhowe** [comment]
added 3 new brand images
still need to know about drawing circles around square images (or at all)

**Comment by billposters** [comment]
yeah square images aren't quite working are they? shall i make them circles?

**Comment by dhowe** [comment]
we can draw them without the bounding circle -- i just need a list of which ones are square, like so:

`'zara', 'xbox', ...`

**Comment by billposters** [comment]
you may have to do this. I'm heading to the space now to begin the mods of the baseplates and have a production meeting with Tom.

**Comment by billposters** [comment]
> we can draw them without the bounding circle -- i just need a list of which ones are square, like so:
> 
> `'zara', 'xbox', ...`

- wil they all be consistent? would look better if it is all consistent

**Comment by dhowe** [comment]
then we need to make the square ones round
