### ISSUE TITLE
Onscreen Keyboard Component

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#54]

**Comment by joseph-allen** [comment]
Some of our inputs will require an on screen keyboard, how will this work on the spectre displays?

**Comment by dhowe** [comment]
https://www.npmjs.com/package/react-simple-keyboard
https://www.npmjs.com/package/react-virtual-keyboard

**Comment by dhowe** [comment]
done -- needs styling

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/58712564-b8d99880-83b8-11e9-9ba6-120ed5ee97ad.png)
