### ISSUE TITLE
OCEAN Sliders should animate into place when OCEANProfile opens

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#541]
start at 0 and ease into correct place

**Comment by cqx931** [comment]
added please check https://github.com/dhowe/spectre/pull/548/commits/1b7484d2a9551d61fbb57987173703f8dd78a2f7

**Comment by dhowe** [comment]
niiiiice

**Comment by dhowe** [comment]
Seems this has affected all sliders, not just the ones in the ocean-profile.

**Comment by dhowe** [comment]
Commented changes in .css -- please uncomment when ready
