### ISSUE TITLE
Distinct visual design for Buttons

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#545]
There are multiple similarly colored circles on pages and it is not always clear to users which are buttons and which are not (there are 11 on the page below,  2 of which are 'clickable'). Is their an easy way to delineate clickable buttons vs icons throughout the site?

![Screen Shot 2020-02-28 at 4 44 48 PM](https://user-images.githubusercontent.com/737638/75524939-dde36080-5a49-11ea-8bad-9b6a97bfc440.png)

**Comment by peterbix** [comment]
Make icons negative - white fill with blue icon
