### ISSUE TITLE
Convert post-exp page to responsive react

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#549]
This is a (long) page of a static HTML that needs to be converted to react, and needs to be responsive as it will be viewed _after_ the installation, on people's own devices. Should go in /spectre/client/src/PostExp

http://www.petercadney.co.uk/designs/spectre/ (zip below) 

[spectre-web.zip](https://github.com/dhowe/spectre/files/4268311/spectre-web.zip)

**Comment by cqx931** [comment]
https://github.com/dhowe/spectre/pull/552
The basic Layout
TODO:

- List style
- Youtube video
- Avatar Image and Ocean Profile

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/spectre/pull/554
https://github.com/dhowe/spectre/pull/554/commits/9ef86c886b15ff6ee40897acceddebc3832b539a
Fixed:
- CSS Style Conflict
- List Style
- Youtube video

https://github.com/dhowe/spectre/pull/554/commits/97f13af3b6aaeb7eea38cf8dfcb6bf80d31aea2d
In this commit, I implemented dynamic Avatar Images. As for Ocean Profile, I am using an image placeholder for now instead. Still need to figure out the CSS for this one if we want it dynamic.

![image](https://user-images.githubusercontent.com/3056154/75616444-d641bb80-5b1e-11ea-870d-2e057263584b.png)

**Comment by dhowe** [comment]
OCEANProfile is dynamic now, but css needs some tweaking (doesn't render correctly in FF)
