### ISSUE TITLE
OceanProfile: highlight dominant trait for user

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#555]
Something like:

![image](https://user-images.githubusercontent.com/737638/75622218-08175880-5bd9-11ea-99d3-098c3865dca6.png)

**Comment by peterbix** [comment]
Is this for the Spectre app or the post-experience website?

**Comment by peterbix** [comment]
I've added to FIgma

**Comment by dhowe** [comment]
spectre-app

**Comment by peterbix** [comment]
I've updated, maybe bold the word 'conscientious' in the paragraphs?

**Comment by dhowe** [comment]
See #565
