### ISSUE TITLE
Error: Unhandled rejection: (TypeError): target.objPron is not a function

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#559]
![Screenshot 2020-03-02 at 11 39 30 AM](https://user-images.githubusercontent.com/4047303/75643876-4c5b3500-5c7b-11ea-9447-d51ee2945b09.png)

I went through the pages from the first page via navigation and it appears on Your-Power page.
It seems to happen to the page afterward that has Ocean Profile.
if closing this error dialog, Ocean Profile tab data is empty when this error happens

**Comment by kennyviperhk** [comment]
seems fixed by your last commit

**Comment by dhowe** [comment]
I've put in a fix for this (assuming its related to re-used emails, which is the only way I can re-create it).

Please let me know if you ASAP if you see it again

**Comment by kennyviperhk** [comment]
seems have not appear again
