### ISSUE TITLE
Highlight dominant trait in Ocean Profile 

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#565]
- [x] Slider should be outlined with 'dominant' diamond as shown
- [ ] Trait name should be bold in text (outlined in red below)

![image](https://user-images.githubusercontent.com/737638/75690316-9248e500-5cdd-11ea-9d59-a2bffe3ceae5.png)

**Comment by billposters** [comment]
![IMG_5082](https://user-images.githubusercontent.com/48989022/75781862-e394bb00-5d55-11ea-87e0-88bb480e65ac.JPG)

**Comment by billposters** [comment]
- no bold on dominant trait, words showing up in red

**Comment by dhowe** [comment]
This page looks good now, but I still feel it is a bit overwhelming to user, all this text and data in the same color/style. @peterbix I wonder if we can use colors to differentiate between the different ocean traits? Perhaps something like:

![image](https://user-images.githubusercontent.com/737638/75969697-47f87b80-5f0a-11ea-8db7-8cf121b8eca0.png)
