### ISSUE TITLE
Add onError images or placeholders for dark-ad page

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#567]
should never see broken images _ever_

**Comment by dhowe** [comment]
@billposters comment if you ever see a broken image (dark-ad is one place)

**Comment by billposters** [comment]
5 of 5 passes had no error on images however that was for V1.0.32

will test latest version now

**Comment by billposters** [comment]
- 1 x user profile pic not loaded / showing in ‘influence a follower’

**Comment by dhowe** [comment]
that really shouldn't happen once we have a few more users with images in the database...

**Comment by dhowe** [comment]
I'm closing but lets keep an eye out for this in the future...
