### ISSUE TITLE
CSS incorrect on Login Page

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#571]
See how Terms of Service is hidden under keyboard (intermittent)

![image](https://user-images.githubusercontent.com/737638/75745320-ec838d80-5d51-11ea-94be-683fdd183c43.png)

**Comment by kennyviperhk** [comment]
it only happens if you have switched the layout/window resolution(landscape portrait) without refresh. 
is it happen on start up process ?

**Comment by dhowe** [comment]
seems to happen intermittently in testing (not sure why) -- can we remove the portrait code for that page, so that it always starts correctly in landscape ?

**Comment by kennyviperhk** [comment]
it is caused by css inside react which it tends to not rerender the screen.
CSS file always refreshes immediately according to screen size.

I added a code that would detect any resolution change and it will refresh once and should fix it.

**Comment by dhowe** [comment]
@billposters pls check if you notice this issue again

**Comment by billposters** [comment]
checked - 1 of 5 passes had this issue

**Comment by billposters** [comment]
no issues after subsequent tests with latest build
