### ISSUE TITLE
Mirror webcam on take-selfie page

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#581]
It is almost impossible to center one's head in the circle as is

**Comment by dhowe** [comment]
This doesn't appear to work in the current build -- please re-check.

**Comment by kennyviperhk** [comment]
can you describe more what is not working? 
i used the mirrored={true} to vertically flipped the image preview of the webcam image, the image preview appears to act like a mirror for me now.

**Comment by dhowe** [comment]
Can you show me where you used the mirrored attribute? https://github.com/dhowe/spectre/blob/master/client/src/Pages/TakeSelfie/TakeSelfie.jsx

**Comment by kennyviperhk** [comment]
the revert i did by mistake removed the attribute on latest repo...i submitted the PR again
