### ISSUE TITLE
Cannot visit post-experience in Firefox

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#588]
![image](https://user-images.githubusercontent.com/737638/76410943-bf775080-63cb-11ea-986b-f7093030af37.png)

**Comment by dhowe** [comment]
@cqx931 can you try vising [[http://localhost:3000/postexp#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQiLCJpYXQiOjE1ODM2NjQ1ODMsImV4cCI6MTYxNTIyMjE4M30.Zinyt8PjJqnZEIVb10jjwzxrIml7x9imDXXik_AdnzU | this link]] this on your machine?

**Comment by cqx931** [comment]
I don't have any issues with visiting the above link from firefox.

**Comment by kennyviperhk** [comment]
firefox security settings / issue?

https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue/12042843#12042843

![Screenshot 2020-03-12 at 1 07 50 PM](https://user-images.githubusercontent.com/4047303/76489164-85a55900-6462-11ea-96b1-d7da634fc806.png)

**Comment by dhowe** [comment]
strange that this just started happening
