### ISSUE TITLE
Error when clicking avatar on /follower page

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/spectre#605]
when click on an avatar, 

<img width="522" alt="Screenshot 2020-03-26 at 10 52 42 AM" src="https://user-images.githubusercontent.com/4047303/77605945-34f92a00-6f51-11ea-98d0-a7c7f63dc868.png">

**Comment by dhowe** [comment]
@kennyviperhk pls verify

**Comment by kennyviperhk** [comment]
it is fixed
