### ISSUE TITLE
Page: Audio-Video Recording Test

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#68]
We need a simple page for testing audio and video recording hardware/software...

**Comment by joseph-allen** [comment]
sure, I thought we descoped this stuff, is this purely for testing?

**Comment by dhowe** [comment]
I think not. Barney, do you want to weigh in here (Is he on github?)

**Comment by joseph-allen** [comment]
it's not in the figma designs anymore, regardless we will need a simple page to test recording to confirm the camera is working and capturable within the UI so worthwhile nonetheless
