### ISSUE TITLE
Discuss hosting plan

### ISSUE THREAD

**Issue by dhowe** [dhowe/spectre#7]
Requirements for back-end: node/express/mongodb exposing REST api
Requirements for front-end:  ??

**Comment by joseph-allen** [comment]
front end should be able to sit on netlify, we may need to mix things up for the offline version though

**Comment by dhowe** [comment]
questions:
a) netlify scaling (for online version), redundancy, costs ?
b) installation version: can we run from static files on an rpi ?

**Comment by joseph-allen** [comment]
netlify is free and designed for scale https://www.smashingmagazine.com/ uses it which is fairly large.
not sure about redundancy

and yes, it's built so it can compile with React and self host, I can set up an image for that on raspberry pi which automatically goes into kiosk mode on startup too.

**Comment by dhowe** [comment]
excellent, let me know when you want to start integrating with the server (its currently running on a dev-server you can access until we pick a dedicated server-host)

**Comment by joseph-allen** [comment]
options should be [here](https://app.netlify.com/teams/dhowe/dns) to do so.

**Comment by dhowe** [comment]
![Screen Shot 2019-04-11 at 11 16 41 AM](https://user-images.githubusercontent.com/737638/55969218-50eab980-5c75-11e9-8694-f18cd8e37cdc.png)

**Comment by joseph-allen** [comment]
tried to save a click, try this!
https://app.netlify.com/dns

**Comment by dhowe** [comment]
on-hold
