### ISSUE TITLE
Store value choice in data layer

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#71]
store the choice of power, etc. in the data layer

**Comment by dhowe** [comment]
Can you we come up a list (from the first 25 pages at least) of data to be stored, so that I can create the database schema?

* name
* login
* login-type (twitter, google, email, etc.)
* gender
* keyword (power, influence, etc)
* answers-to-questions
* ...

**Comment by joseph-allen** [comment]
we can, but it may be worthwhile thinking about changes to the journey? if we add new features we don't want to change the DB for example.

what we store will be self-documenting as we build the product
