### ISSUE TITLE
Login: Functionality

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#79]
The Login page needs to store the input login/loginType in the data layer

**Comment by dhowe** [comment]
Login page needs to send {login,loginType['twitter', 'google', 'facebook', 'email']} to database, gets user back with _id property, which is unique key.

If data is invalid or login/loginType already exists, display message and repeat 

Server-route: /spectre/users [POST]

**Comment by dhowe** [comment]
The functionality is a little bit strange here. 
There are two basic options from the  user perspective
1. create a new login with email/password (loginType=email)
2. login with an existing social media account (loginType['twitter', 'google', 'facebook', 'email'])

Case 1 is simple. In Case 2 we want the user _to think_ they are logging in via social media, but actually we are only storing their login/loginType as unique/primary key.

But, for Case 2, we may need to create a 2nd page, styled according to the social media type, where they enter their info. 

In all cases, the password is simply ignored.

**Comment by joseph-allen** [comment]
Agreed, current implementation is somebody else's component.
