### ISSUE TITLE
InfluenceAFollower: Functionality

### ISSUE THREAD

**Issue by joseph-allen** [dhowe/spectre#97]
These faces and names are supposed to be grabbed from our backend?
@dhowe any details here?
Alternatively, any harm in faking this with dummy users for now.

**Comment by dhowe** [comment]
No problem using dummy data for now, though we can test whenever you like (we just need data in the db). The route is /spectre/users/similar/:id?limit=k where ':id' is the previously created user id, and k is the max number of results you want back (8 I believe in the figma mockup).

**Comment by dhowe** [comment]
Server:route /spectre/users/similar/:id?limit=k where ':id' is the previously created user id, and k is the max number of results you want back (10 is default, 8 is what I saw in the last figma)
